// Code generated by goctl. DO NOT EDIT!
// Source: transaction.proto

package server

import (
	"context"
	"github.com/copo888/transaction_service/rpc/internal/logic"
	"github.com/copo888/transaction_service/rpc/internal/svc"
	"github.com/copo888/transaction_service/rpc/transaction"
	"google.golang.org/grpc/health/grpc_health_v1"
)

type TransactionServer struct {
	svcCtx *svc.ServiceContext
	transaction.UnimplementedTransactionServer
}

func NewTransactionServer(svcCtx *svc.ServiceContext) *TransactionServer {
	return &TransactionServer{
		svcCtx: svcCtx,
	}
}

func (s *TransactionServer) Check(ctx context.Context, req *grpc_health_v1.HealthCheckRequest) (*grpc_health_v1.HealthCheckResponse, error) {
	return &grpc_health_v1.HealthCheckResponse{
		Status: grpc_health_v1.HealthCheckResponse_SERVING,
	}, nil
}

func (s *TransactionServer) Watch(req *grpc_health_v1.HealthCheckRequest, w grpc_health_v1.Health_WatchServer) error {
	return nil
}

func (s *TransactionServer) ProxyOrderTranaction_DFB(ctx context.Context, in *transaction.ProxyOrderRequest) (*transaction.ProxyOrderResponse, error) {
	l := logic.NewProxyOrderTranactionDFBLogic(ctx, s.svcCtx)
	return l.ProxyOrderTranaction_DFB(in)
}

func (s *TransactionServer) ProxyOrderTranaction_XFB(ctx context.Context, in *transaction.ProxyOrderRequest) (*transaction.ProxyOrderResponse, error) {
	l := logic.NewProxyOrderTranactionXFBLogic(ctx, s.svcCtx)
	return l.ProxyOrderTranaction_XFB(in)
}

func (s *TransactionServer) PayOrderTranaction(ctx context.Context, in *transaction.PayOrderRequest) (*transaction.PayOrderResponse, error) {
	l := logic.NewPayOrderTranactionLogic(ctx, s.svcCtx)
	return l.PayOrderTranaction(in)
}

func (s *TransactionServer) InternalOrderTransaction(ctx context.Context, in *transaction.InternalOrderRequest) (*transaction.InternalOrderResponse, error) {
	l := logic.NewInternalOrderTransactionLogic(ctx, s.svcCtx)
	return l.InternalOrderTransaction(in)
}

func (s *TransactionServer) WithdrawOrderTransaction(ctx context.Context, in *transaction.WithdrawOrderRequest) (*transaction.WithdrawOrderResponse, error) {
	l := logic.NewWithdrawOrderTransactionLogic(ctx, s.svcCtx)
	return l.WithdrawOrderTransaction(in)
}

func (s *TransactionServer) PayCallBackTranaction(ctx context.Context, in *transaction.PayCallBackRequest) (*transaction.PayCallBackResponse, error) {
	l := logic.NewPayCallBackTranactionLogic(ctx, s.svcCtx)
	return l.PayCallBackTranaction(in)
}

func (s *TransactionServer) InternalReviewSuccessTransaction(ctx context.Context, in *transaction.InternalReviewSuccessRequest) (*transaction.InternalReviewSuccessResponse, error) {
	l := logic.NewInternalReviewSuccessTransactionLogic(ctx, s.svcCtx)
	return l.InternalReviewSuccessTransaction(in)
}

func (s *TransactionServer) WithdrawReviewFailTransaction(ctx context.Context, in *transaction.WithdrawReviewFailRequest) (*transaction.WithdrawReviewFailResponse, error) {
	l := logic.NewWithdrawReviewFailTransactionLogic(ctx, s.svcCtx)
	return l.WithdrawReviewFailTransaction(in)
}

func (s *TransactionServer) WithdrawReviewSuccessTransaction(ctx context.Context, in *transaction.WithdrawReviewSuccessRequest) (*transaction.WithdrawReviewSuccessResponse, error) {
	l := logic.NewWithdrawReviewSuccessTransactionLogic(ctx, s.svcCtx)
	return l.WithdrawReviewSuccessTransaction(in)
}
