// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyOrderRequest struct {
	Req                  *ProxyPayOrderRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	BalanceType          string                `protobuf:"bytes,3,opt,name=balanceType,proto3" json:"balanceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProxyOrderRequest) Reset()         { *m = ProxyOrderRequest{} }
func (m *ProxyOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderRequest) ProtoMessage()    {}
func (*ProxyOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *ProxyOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderRequest.Unmarshal(m, b)
}
func (m *ProxyOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderRequest.Marshal(b, m, deterministic)
}
func (m *ProxyOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderRequest.Merge(m, src)
}
func (m *ProxyOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderRequest.Size(m)
}
func (m *ProxyOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderRequest proto.InternalMessageInfo

func (m *ProxyOrderRequest) GetReq() *ProxyPayOrderRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ProxyOrderRequest) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *ProxyOrderRequest) GetBalanceType() string {
	if m != nil {
		return m.BalanceType
	}
	return ""
}

type ProxyOrderResponse struct {
	ProxyOrderNo         string   `protobuf:"bytes,1,opt,name=ProxyOrderNo,proto3" json:"ProxyOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyOrderResponse) Reset()         { *m = ProxyOrderResponse{} }
func (m *ProxyOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderResponse) ProtoMessage()    {}
func (*ProxyOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ProxyOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderResponse.Unmarshal(m, b)
}
func (m *ProxyOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderResponse.Marshal(b, m, deterministic)
}
func (m *ProxyOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderResponse.Merge(m, src)
}
func (m *ProxyOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderResponse.Size(m)
}
func (m *ProxyOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderResponse proto.InternalMessageInfo

func (m *ProxyOrderResponse) GetProxyOrderNo() string {
	if m != nil {
		return m.ProxyOrderNo
	}
	return ""
}

type ProxyOrderResp_XFB struct {
	ProxyOrderNo         string   `protobuf:"bytes,1,opt,name=ProxyOrderNo,proto3" json:"ProxyOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyOrderResp_XFB) Reset()         { *m = ProxyOrderResp_XFB{} }
func (m *ProxyOrderResp_XFB) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderResp_XFB) ProtoMessage()    {}
func (*ProxyOrderResp_XFB) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *ProxyOrderResp_XFB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderResp_XFB.Unmarshal(m, b)
}
func (m *ProxyOrderResp_XFB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderResp_XFB.Marshal(b, m, deterministic)
}
func (m *ProxyOrderResp_XFB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderResp_XFB.Merge(m, src)
}
func (m *ProxyOrderResp_XFB) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderResp_XFB.Size(m)
}
func (m *ProxyOrderResp_XFB) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderResp_XFB.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderResp_XFB proto.InternalMessageInfo

func (m *ProxyOrderResp_XFB) GetProxyOrderNo() string {
	if m != nil {
		return m.ProxyOrderNo
	}
	return ""
}

type ProxyPayOrderRequest struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	OrderNo              string   `protobuf:"bytes,6,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	BankId               string   `protobuf:"bytes,7,opt,name=BankId,proto3" json:"BankId,omitempty"`
	BankName             string   `protobuf:"bytes,8,opt,name=BankName,proto3" json:"BankName,omitempty"`
	BankProvince         string   `protobuf:"bytes,9,opt,name=BankProvince,proto3" json:"BankProvince,omitempty"`
	BankCity             string   `protobuf:"bytes,10,opt,name=BankCity,proto3" json:"BankCity,omitempty"`
	BranchName           string   `protobuf:"bytes,11,opt,name=BranchName,proto3" json:"BranchName,omitempty"`
	BankNo               string   `protobuf:"bytes,12,opt,name=BankNo,proto3" json:"BankNo,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,13,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	DefrayName           string   `protobuf:"bytes,14,opt,name=DefrayName,proto3" json:"DefrayName,omitempty"`
	DefrayId             string   `protobuf:"bytes,15,opt,name=DefrayId,proto3" json:"DefrayId,omitempty"`
	DefrayMobile         string   `protobuf:"bytes,16,opt,name=DefrayMobile,proto3" json:"DefrayMobile,omitempty"`
	DefrayEmail          string   `protobuf:"bytes,17,opt,name=DefrayEmail,proto3" json:"DefrayEmail,omitempty"`
	Currency             string   `protobuf:"bytes,18,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayTypeSubNo         string   `protobuf:"bytes,19,opt,name=PayTypeSubNo,proto3" json:"PayTypeSubNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyPayOrderRequest) Reset()         { *m = ProxyPayOrderRequest{} }
func (m *ProxyPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyPayOrderRequest) ProtoMessage()    {}
func (*ProxyPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *ProxyPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyPayOrderRequest.Unmarshal(m, b)
}
func (m *ProxyPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *ProxyPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyPayOrderRequest.Merge(m, src)
}
func (m *ProxyPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyPayOrderRequest.Size(m)
}
func (m *ProxyPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyPayOrderRequest proto.InternalMessageInfo

func (m *ProxyPayOrderRequest) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankId() string {
	if m != nil {
		return m.BankId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankProvince() string {
	if m != nil {
		return m.BankProvince
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankCity() string {
	if m != nil {
		return m.BankCity
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankNo() string {
	if m != nil {
		return m.BankNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *ProxyPayOrderRequest) GetDefrayName() string {
	if m != nil {
		return m.DefrayName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayId() string {
	if m != nil {
		return m.DefrayId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayMobile() string {
	if m != nil {
		return m.DefrayMobile
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayEmail() string {
	if m != nil {
		return m.DefrayEmail
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetPayTypeSubNo() string {
	if m != nil {
		return m.PayTypeSubNo
	}
	return ""
}

type CorrespondMerChnRate struct {
	MerchantCode         string   `protobuf:"bytes,1,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	ChannelPayTypesCode  string   `protobuf:"bytes,2,opt,name=ChannelPayTypesCode,proto3" json:"ChannelPayTypesCode,omitempty"`
	ChannelCode          string   `protobuf:"bytes,3,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	PayTypeCode          string   `protobuf:"bytes,4,opt,name=PayTypeCode,proto3" json:"PayTypeCode,omitempty"`
	PayTypeCodeNum       string   `protobuf:"bytes,5,opt,name=PayTypeCodeNum,proto3" json:"PayTypeCodeNum,omitempty"`
	Designation          string   `protobuf:"bytes,6,opt,name=Designation,proto3" json:"Designation,omitempty"`
	DesignationNo        string   `protobuf:"bytes,7,opt,name=DesignationNo,proto3" json:"DesignationNo,omitempty"`
	Fee                  float64  `protobuf:"fixed64,8,opt,name=Fee,proto3" json:"Fee,omitempty"`
	HandlingFee          float64  `protobuf:"fixed64,9,opt,name=HandlingFee,proto3" json:"HandlingFee,omitempty"`
	ChFee                float64  `protobuf:"fixed64,10,opt,name=ChFee,proto3" json:"ChFee,omitempty"`
	ChHandlingFee        float64  `protobuf:"fixed64,11,opt,name=ChHandlingFee,proto3" json:"ChHandlingFee,omitempty"`
	SingleMinCharge      float64  `protobuf:"fixed64,12,opt,name=SingleMinCharge,proto3" json:"SingleMinCharge,omitempty"`
	SingleMaxCharge      float64  `protobuf:"fixed64,13,opt,name=SingleMaxCharge,proto3" json:"SingleMaxCharge,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,14,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	ApiUrl               string   `protobuf:"bytes,15,opt,name=ApiUrl,proto3" json:"ApiUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorrespondMerChnRate) Reset()         { *m = CorrespondMerChnRate{} }
func (m *CorrespondMerChnRate) String() string { return proto.CompactTextString(m) }
func (*CorrespondMerChnRate) ProtoMessage()    {}
func (*CorrespondMerChnRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *CorrespondMerChnRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrespondMerChnRate.Unmarshal(m, b)
}
func (m *CorrespondMerChnRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrespondMerChnRate.Marshal(b, m, deterministic)
}
func (m *CorrespondMerChnRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrespondMerChnRate.Merge(m, src)
}
func (m *CorrespondMerChnRate) XXX_Size() int {
	return xxx_messageInfo_CorrespondMerChnRate.Size(m)
}
func (m *CorrespondMerChnRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrespondMerChnRate.DiscardUnknown(m)
}

var xxx_messageInfo_CorrespondMerChnRate proto.InternalMessageInfo

func (m *CorrespondMerChnRate) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelPayTypesCode() string {
	if m != nil {
		return m.ChannelPayTypesCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCodeNum() string {
	if m != nil {
		return m.PayTypeCodeNum
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignationNo() string {
	if m != nil {
		return m.DesignationNo
	}
	return ""
}

func (m *CorrespondMerChnRate) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetHandlingFee() float64 {
	if m != nil {
		return m.HandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChFee() float64 {
	if m != nil {
		return m.ChFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChHandlingFee() float64 {
	if m != nil {
		return m.ChHandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMinCharge() float64 {
	if m != nil {
		return m.SingleMinCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMaxCharge() float64 {
	if m != nil {
		return m.SingleMaxCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

type PayOrderRequest struct {
	PayOrder             *PayOrder             `protobuf:"bytes,1,opt,name=payOrder,proto3" json:"payOrder,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	OrderNo              string                `protobuf:"bytes,3,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	ChannelOrderNo       string                `protobuf:"bytes,4,opt,name=ChannelOrderNo,proto3" json:"ChannelOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PayOrderRequest) Reset()         { *m = PayOrderRequest{} }
func (m *PayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderRequest) ProtoMessage()    {}
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *PayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderRequest.Unmarshal(m, b)
}
func (m *PayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderRequest.Merge(m, src)
}
func (m *PayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderRequest.Size(m)
}
func (m *PayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderRequest proto.InternalMessageInfo

func (m *PayOrderRequest) GetPayOrder() *PayOrder {
	if m != nil {
		return m.PayOrder
	}
	return nil
}

func (m *PayOrderRequest) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *PayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrderRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

type PayOrderResponse struct {
	PayOrderNo           string   `protobuf:"bytes,1,opt,name=PayOrderNo,proto3" json:"PayOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderResponse) Reset()         { *m = PayOrderResponse{} }
func (m *PayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PayOrderResponse) ProtoMessage()    {}
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *PayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderResponse.Unmarshal(m, b)
}
func (m *PayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderResponse.Marshal(b, m, deterministic)
}
func (m *PayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderResponse.Merge(m, src)
}
func (m *PayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PayOrderResponse.Size(m)
}
func (m *PayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderResponse proto.InternalMessageInfo

func (m *PayOrderResponse) GetPayOrderNo() string {
	if m != nil {
		return m.PayOrderNo
	}
	return ""
}

type PayOrder struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,3,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	PageUrl              string   `protobuf:"bytes,4,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=Sign,proto3" json:"Sign,omitempty"`
	JumpType             string   `protobuf:"bytes,7,opt,name=JumpType,proto3" json:"JumpType,omitempty"`
	LoginType            string   `protobuf:"bytes,8,opt,name=LoginType,proto3" json:"LoginType,omitempty"`
	OrderNo              string   `protobuf:"bytes,9,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	OrderAmount          string   `protobuf:"bytes,10,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	Currency             string   `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayType              string   `protobuf:"bytes,12,opt,name=PayType,proto3" json:"PayType,omitempty"`
	OrderTime            string   `protobuf:"bytes,13,opt,name=OrderTime,proto3" json:"OrderTime,omitempty"`
	OrderName            string   `protobuf:"bytes,14,opt,name=OrderName,proto3" json:"OrderName,omitempty"`
	BankCode             string   `protobuf:"bytes,15,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	Phone                string   `protobuf:"bytes,16,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PayTypeNo            string   `protobuf:"bytes,17,opt,name=PayTypeNo,proto3" json:"PayTypeNo,omitempty"`
	UserId               string   `protobuf:"bytes,18,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MerchantLevel        string   `protobuf:"bytes,19,opt,name=MerchantLevel,proto3" json:"MerchantLevel,omitempty"`
	UserIp               string   `protobuf:"bytes,20,opt,name=UserIp,proto3" json:"UserIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrder) Reset()         { *m = PayOrder{} }
func (m *PayOrder) String() string { return proto.CompactTextString(m) }
func (*PayOrder) ProtoMessage()    {}
func (*PayOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *PayOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrder.Unmarshal(m, b)
}
func (m *PayOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrder.Marshal(b, m, deterministic)
}
func (m *PayOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrder.Merge(m, src)
}
func (m *PayOrder) XXX_Size() int {
	return xxx_messageInfo_PayOrder.Size(m)
}
func (m *PayOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrder proto.InternalMessageInfo

func (m *PayOrder) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *PayOrder) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *PayOrder) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *PayOrder) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *PayOrder) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PayOrder) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayOrder) GetJumpType() string {
	if m != nil {
		return m.JumpType
	}
	return ""
}

func (m *PayOrder) GetLoginType() string {
	if m != nil {
		return m.LoginType
	}
	return ""
}

func (m *PayOrder) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrder) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *PayOrder) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PayOrder) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PayOrder) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *PayOrder) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

func (m *PayOrder) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *PayOrder) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PayOrder) GetPayTypeNo() string {
	if m != nil {
		return m.PayTypeNo
	}
	return ""
}

func (m *PayOrder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PayOrder) GetMerchantLevel() string {
	if m != nil {
		return m.MerchantLevel
	}
	return ""
}

func (m *PayOrder) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyOrderRequest)(nil), "transaction.ProxyOrderRequest")
	proto.RegisterType((*ProxyOrderResponse)(nil), "transaction.ProxyOrderResponse")
	proto.RegisterType((*ProxyOrderResp_XFB)(nil), "transaction.ProxyOrderResp_XFB")
	proto.RegisterType((*ProxyPayOrderRequest)(nil), "transaction.ProxyPayOrderRequest")
	proto.RegisterType((*CorrespondMerChnRate)(nil), "transaction.CorrespondMerChnRate")
	proto.RegisterType((*PayOrderRequest)(nil), "transaction.PayOrderRequest")
	proto.RegisterType((*PayOrderResponse)(nil), "transaction.PayOrderResponse")
	proto.RegisterType((*PayOrder)(nil), "transaction.PayOrder")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x96, 0x49, 0xda, 0xc6, 0x27, 0xdb, 0xa6, 0x9d, 0x0d, 0x68, 0x54, 0x2d, 0xa5, 0x44, 0x68,
	0xd5, 0xab, 0x02, 0x5d, 0x21, 0x71, 0xdb, 0x1a, 0x56, 0x14, 0xb5, 0x26, 0xb8, 0x5d, 0x81, 0xb8,
	0x41, 0x53, 0x7b, 0xd6, 0xb6, 0x70, 0x66, 0xbc, 0x63, 0x67, 0xb5, 0x79, 0x1b, 0x78, 0x0c, 0x2e,
	0x90, 0x78, 0x02, 0x9e, 0x09, 0x9d, 0xf9, 0x89, 0xc7, 0xd9, 0x2c, 0x02, 0x71, 0xe7, 0xef, 0x3b,
	0x3f, 0x3e, 0x67, 0xfc, 0xcd, 0x97, 0xc0, 0x51, 0xab, 0x98, 0x68, 0x58, 0xda, 0x96, 0x52, 0x9c,
	0xd7, 0x4a, 0xb6, 0x92, 0x8c, 0x3d, 0x6a, 0xf6, 0x5b, 0x00, 0x47, 0x73, 0x25, 0xdf, 0xac, 0xbe,
	0x53, 0x19, 0x57, 0x09, 0x7f, 0xb5, 0xe4, 0x4d, 0x4b, 0x9e, 0xc1, 0x40, 0xf1, 0x57, 0x34, 0x38,
	0x0d, 0xce, 0xc6, 0x17, 0x1f, 0x9f, 0xfb, 0x3d, 0x74, 0xf2, 0x9c, 0xf5, 0xf2, 0x13, 0xcc, 0x26,
	0x5f, 0xc0, 0x50, 0xb1, 0x96, 0xd3, 0xf7, 0xb6, 0x54, 0x45, 0x52, 0x29, 0xde, 0xd4, 0x52, 0x64,
	0xb7, 0x5c, 0x45, 0x85, 0x48, 0x58, 0xcb, 0x13, 0x9d, 0x4e, 0x4e, 0x61, 0xfc, 0xc0, 0x2a, 0x26,
	0x52, 0x7e, 0xbf, 0xaa, 0x39, 0x1d, 0x9c, 0x06, 0x67, 0x61, 0xe2, 0x53, 0xb3, 0x2f, 0x81, 0xf8,
	0x23, 0x62, 0x9b, 0x86, 0x93, 0x19, 0x3c, 0xea, 0xd8, 0x58, 0xea, 0x61, 0xc3, 0xa4, 0xc7, 0xbd,
	0x5d, 0xf9, 0xf3, 0x8f, 0xcf, 0xaf, 0xfe, 0x55, 0xe5, 0x5f, 0x43, 0x98, 0x6e, 0x5b, 0x95, 0x9c,
	0x00, 0x5c, 0xa6, 0x29, 0x6f, 0x1a, 0x3d, 0xad, 0x29, 0xf5, 0x18, 0x8c, 0xdf, 0x72, 0x95, 0x16,
	0x4c, 0xb4, 0xd7, 0x99, 0x3e, 0x8b, 0x30, 0xf1, 0x18, 0x42, 0x60, 0x78, 0x57, 0xe6, 0xc2, 0xee,
	0xa9, 0x9f, 0xc9, 0x13, 0x08, 0x63, 0xd9, 0x96, 0x2f, 0x57, 0x2f, 0x54, 0x45, 0x87, 0x3a, 0xd0,
	0x11, 0xe4, 0x18, 0x46, 0x37, 0x4c, 0xe4, 0x4b, 0x96, 0x73, 0xba, 0xa3, 0x83, 0x6b, 0x4c, 0x28,
	0xec, 0xb9, 0x2d, 0x76, 0x75, 0xc8, 0x41, 0xf2, 0x01, 0xec, 0x5e, 0x31, 0xf1, 0xcb, 0x75, 0x46,
	0xf7, 0x74, 0xc0, 0x22, 0xec, 0x86, 0x4f, 0x31, 0x5b, 0x70, 0x3a, 0x32, 0xdd, 0x1c, 0xc6, 0x83,
	0xc1, 0xe7, 0xb9, 0x92, 0xaf, 0x4b, 0x91, 0x72, 0x1a, 0x9a, 0x83, 0xf1, 0x39, 0x57, 0x1f, 0x95,
	0xed, 0x8a, 0x42, 0x57, 0x8f, 0x18, 0x77, 0xbf, 0x52, 0x4c, 0xa4, 0x85, 0xee, 0x3e, 0x36, 0xbb,
	0x77, 0x8c, 0x9b, 0x29, 0x96, 0xf4, 0x51, 0x37, 0x53, 0x2c, 0x51, 0x02, 0x7a, 0xec, 0xcb, 0x85,
	0x5c, 0x8a, 0x96, 0xee, 0x9f, 0x06, 0x67, 0x41, 0xe2, 0x53, 0xd8, 0xf9, 0x2b, 0xfe, 0x52, 0xb1,
	0x95, 0xee, 0x7c, 0x60, 0x3a, 0x77, 0x0c, 0x4e, 0x65, 0xd0, 0x75, 0x46, 0x27, 0x66, 0x2a, 0x87,
	0x71, 0x2b, 0xf3, 0x7c, 0x2b, 0x1f, 0xca, 0x8a, 0xd3, 0x43, 0xb3, 0x95, 0xcf, 0xe1, 0x04, 0x06,
	0x7f, 0xbd, 0x60, 0x65, 0x45, 0x8f, 0x8c, 0x08, 0x3d, 0x0a, 0xdf, 0x10, 0x2d, 0x95, 0xe2, 0x22,
	0x5d, 0x51, 0x62, 0xde, 0xe0, 0xb0, 0x16, 0x14, 0x5b, 0xe1, 0xe7, 0xbf, 0x5b, 0x3e, 0xc4, 0x92,
	0x3e, 0xb6, 0x82, 0xf2, 0xb8, 0xd9, 0xaf, 0x43, 0x98, 0x6e, 0xbb, 0x05, 0x58, 0xec, 0xe4, 0x11,
	0xc9, 0xcc, 0x49, 0xaa, 0xc7, 0x91, 0xcf, 0xe0, 0x71, 0x54, 0x30, 0x21, 0x78, 0x65, 0x7b, 0x36,
	0x3a, 0xd5, 0xa8, 0x6b, 0x5b, 0x08, 0x17, 0xb2, 0xb4, 0xce, 0xb4, 0xb7, 0xca, 0xa3, 0x30, 0xc3,
	0x56, 0xe8, 0x0c, 0x23, 0x3b, 0x9f, 0x22, 0x4f, 0xe1, 0xc0, 0x83, 0xf1, 0x72, 0x61, 0xe5, 0xb7,
	0xc1, 0x9a, 0xc3, 0x6b, 0xca, 0x5c, 0x30, 0xbc, 0xeb, 0x56, 0x88, 0x3e, 0x45, 0x3e, 0x81, 0x7d,
	0x0f, 0xc6, 0xd2, 0x6a, 0xb2, 0x4f, 0x92, 0x43, 0x18, 0x3c, 0xe7, 0x46, 0x95, 0x41, 0x82, 0x8f,
	0xd8, 0xf9, 0x1b, 0x26, 0xb2, 0xaa, 0x14, 0x39, 0x46, 0x42, 0x23, 0x0c, 0x8f, 0x22, 0x53, 0xd8,
	0x89, 0x0a, 0x8c, 0x81, 0x8e, 0x19, 0x80, 0xef, 0x8b, 0x0a, 0xbf, 0x72, 0xac, 0xa3, 0x7d, 0x92,
	0x9c, 0xc1, 0xe4, 0xae, 0x14, 0x79, 0xc5, 0x6f, 0x4b, 0x11, 0x15, 0x4c, 0xe5, 0x5c, 0xeb, 0x32,
	0x48, 0x36, 0x69, 0x2f, 0x93, 0xbd, 0xb1, 0x99, 0xfb, 0xbd, 0x4c, 0x47, 0xe3, 0xd7, 0x74, 0xb2,
	0xd0, 0xc7, 0x6a, 0xa4, 0xda, 0xe3, 0xf0, 0x1a, 0x5c, 0xd6, 0x25, 0xde, 0x75, 0x23, 0x55, 0x8b,
	0x66, 0x7f, 0x04, 0x30, 0xd9, 0xb4, 0x9b, 0xcf, 0x61, 0x54, 0x5b, 0xca, 0xda, 0xf1, 0xfb, 0x7d,
	0x3b, 0x76, 0xf9, 0xeb, 0x34, 0xf4, 0xe1, 0xe4, 0xbf, 0xf9, 0xb0, 0xd6, 0xa1, 0x67, 0x25, 0x83,
	0xbe, 0x95, 0x3c, 0x85, 0x03, 0x2b, 0x1c, 0x97, 0x60, 0xc4, 0xb2, 0xc1, 0xce, 0x2e, 0xe0, 0xb0,
	0x1b, 0xdf, 0xba, 0xf4, 0x09, 0x80, 0xe3, 0xd6, 0x4e, 0xeb, 0x31, 0xb3, 0x3f, 0x87, 0x30, 0x72,
	0xf0, 0x7f, 0x7b, 0x6b, 0xcf, 0x47, 0x07, 0x9b, 0x3e, 0x4a, 0x61, 0x6f, 0xce, 0x72, 0xde, 0x79,
	0xac, 0x83, 0xff, 0xe8, 0xb0, 0xce, 0xaf, 0x77, 0x3d, 0xbf, 0x3e, 0x86, 0xd1, 0xb7, 0xcb, 0x45,
	0xad, 0xa7, 0x34, 0x4a, 0x5e, 0x63, 0x9c, 0xe1, 0x46, 0xe6, 0xa5, 0xd0, 0x41, 0x63, 0xb0, 0x1d,
	0xe1, 0x1f, 0x72, 0xd8, 0x3f, 0xe4, 0x0d, 0x0f, 0x34, 0xd6, 0xda, 0xf3, 0x40, 0xdf, 0x81, 0xc6,
	0x1b, 0x0e, 0xa4, 0x77, 0xd3, 0x97, 0xd2, 0x5a, 0xab, 0x83, 0x38, 0x8f, 0x6e, 0x72, 0x5f, 0x2e,
	0x8c, 0x68, 0xc3, 0xa4, 0x23, 0xd6, 0x51, 0xcf, 0x56, 0x3b, 0x62, 0xed, 0xf5, 0x28, 0xe4, 0x89,
	0xe7, 0xf5, 0x28, 0xe2, 0x29, 0xec, 0xcc, 0x0b, 0x29, 0x9c, 0x9d, 0x1a, 0x80, 0xfd, 0xec, 0x8b,
	0x63, 0x69, 0x5d, 0xb4, 0x23, 0x50, 0xf8, 0x2f, 0x1a, 0xae, 0xae, 0x33, 0xeb, 0xa0, 0x16, 0xe1,
	0x75, 0x75, 0x5f, 0xf1, 0x86, 0xbf, 0xe6, 0x95, 0x35, 0xd0, 0x3e, 0xb9, 0xae, 0xae, 0xe9, 0xd4,
	0xab, 0xae, 0x2f, 0x7e, 0x0f, 0x60, 0x7c, 0xdf, 0x69, 0x9c, 0xfc, 0x60, 0x7f, 0xb9, 0xcd, 0x96,
	0x8a, 0x09, 0xcb, 0x9f, 0xbc, 0xfd, 0x3f, 0xc6, 0xbf, 0x6a, 0xc7, 0x1f, 0xbd, 0x33, 0x6e, 0xb5,
	0xfc, 0x3d, 0x10, 0x27, 0x55, 0xaf, 0xed, 0x93, 0xed, 0xf7, 0xd1, 0x36, 0xfd, 0xf0, 0x1d, 0x51,
	0xd3, 0xf2, 0x6a, 0xf2, 0xd3, 0xfe, 0xf9, 0xa7, 0x5e, 0xc6, 0xc3, 0xae, 0xfe, 0x8f, 0xf6, 0xec,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xc3, 0xf9, 0x7f, 0xb8, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	ProxyOrderTranaction(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error)
	PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) ProxyOrderTranaction(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error) {
	out := new(ProxyOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/ProxyOrderTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error) {
	out := new(PayOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/PayOrderTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	ProxyOrderTranaction(context.Context, *ProxyOrderRequest) (*ProxyOrderResponse, error)
	PayOrderTranaction(context.Context, *PayOrderRequest) (*PayOrderResponse, error)
}

// UnimplementedTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (*UnimplementedTransactionServer) ProxyOrderTranaction(ctx context.Context, req *ProxyOrderRequest) (*ProxyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyOrderTranaction not implemented")
}
func (*UnimplementedTransactionServer) PayOrderTranaction(ctx context.Context, req *PayOrderRequest) (*PayOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrderTranaction not implemented")
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_ProxyOrderTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).ProxyOrderTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/ProxyOrderTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).ProxyOrderTranaction(ctx, req.(*ProxyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_PayOrderTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).PayOrderTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/PayOrderTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).PayOrderTranaction(ctx, req.(*PayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyOrderTranaction",
			Handler:    _Transaction_ProxyOrderTranaction_Handler,
		},
		{
			MethodName: "PayOrderTranaction",
			Handler:    _Transaction_PayOrderTranaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
