// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyOrderReq_DFB struct {
	Req                  *ProxyPayOrderRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	BalanceType          string                `protobuf:"bytes,3,opt,name=balanceType,proto3" json:"balanceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProxyOrderReq_DFB) Reset()         { *m = ProxyOrderReq_DFB{} }
func (m *ProxyOrderReq_DFB) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderReq_DFB) ProtoMessage()    {}
func (*ProxyOrderReq_DFB) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *ProxyOrderReq_DFB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderReq_DFB.Unmarshal(m, b)
}
func (m *ProxyOrderReq_DFB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderReq_DFB.Marshal(b, m, deterministic)
}
func (m *ProxyOrderReq_DFB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderReq_DFB.Merge(m, src)
}
func (m *ProxyOrderReq_DFB) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderReq_DFB.Size(m)
}
func (m *ProxyOrderReq_DFB) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderReq_DFB.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderReq_DFB proto.InternalMessageInfo

func (m *ProxyOrderReq_DFB) GetReq() *ProxyPayOrderRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ProxyOrderReq_DFB) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *ProxyOrderReq_DFB) GetBalanceType() string {
	if m != nil {
		return m.BalanceType
	}
	return ""
}

type ProxyOrderResp_DFB struct {
	ProxyOrderNo         string   `protobuf:"bytes,1,opt,name=ProxyOrderNo,proto3" json:"ProxyOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyOrderResp_DFB) Reset()         { *m = ProxyOrderResp_DFB{} }
func (m *ProxyOrderResp_DFB) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderResp_DFB) ProtoMessage()    {}
func (*ProxyOrderResp_DFB) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ProxyOrderResp_DFB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderResp_DFB.Unmarshal(m, b)
}
func (m *ProxyOrderResp_DFB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderResp_DFB.Marshal(b, m, deterministic)
}
func (m *ProxyOrderResp_DFB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderResp_DFB.Merge(m, src)
}
func (m *ProxyOrderResp_DFB) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderResp_DFB.Size(m)
}
func (m *ProxyOrderResp_DFB) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderResp_DFB.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderResp_DFB proto.InternalMessageInfo

func (m *ProxyOrderResp_DFB) GetProxyOrderNo() string {
	if m != nil {
		return m.ProxyOrderNo
	}
	return ""
}

type ProxyPayOrderRequest struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	OrderNo              string   `protobuf:"bytes,6,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	BankId               string   `protobuf:"bytes,7,opt,name=BankId,proto3" json:"BankId,omitempty"`
	BankName             string   `protobuf:"bytes,8,opt,name=BankName,proto3" json:"BankName,omitempty"`
	BankProvince         string   `protobuf:"bytes,9,opt,name=BankProvince,proto3" json:"BankProvince,omitempty"`
	BankCity             string   `protobuf:"bytes,10,opt,name=BankCity,proto3" json:"BankCity,omitempty"`
	BranchName           string   `protobuf:"bytes,11,opt,name=BranchName,proto3" json:"BranchName,omitempty"`
	BankNo               string   `protobuf:"bytes,12,opt,name=BankNo,proto3" json:"BankNo,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,13,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	DefrayName           string   `protobuf:"bytes,14,opt,name=DefrayName,proto3" json:"DefrayName,omitempty"`
	DefrayId             string   `protobuf:"bytes,15,opt,name=DefrayId,proto3" json:"DefrayId,omitempty"`
	DefrayMobile         string   `protobuf:"bytes,16,opt,name=DefrayMobile,proto3" json:"DefrayMobile,omitempty"`
	DefrayEmail          string   `protobuf:"bytes,17,opt,name=DefrayEmail,proto3" json:"DefrayEmail,omitempty"`
	Currency             string   `protobuf:"bytes,18,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayTypeSubNo         string   `protobuf:"bytes,19,opt,name=PayTypeSubNo,proto3" json:"PayTypeSubNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyPayOrderRequest) Reset()         { *m = ProxyPayOrderRequest{} }
func (m *ProxyPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyPayOrderRequest) ProtoMessage()    {}
func (*ProxyPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *ProxyPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyPayOrderRequest.Unmarshal(m, b)
}
func (m *ProxyPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *ProxyPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyPayOrderRequest.Merge(m, src)
}
func (m *ProxyPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyPayOrderRequest.Size(m)
}
func (m *ProxyPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyPayOrderRequest proto.InternalMessageInfo

func (m *ProxyPayOrderRequest) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankId() string {
	if m != nil {
		return m.BankId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankProvince() string {
	if m != nil {
		return m.BankProvince
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankCity() string {
	if m != nil {
		return m.BankCity
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankNo() string {
	if m != nil {
		return m.BankNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *ProxyPayOrderRequest) GetDefrayName() string {
	if m != nil {
		return m.DefrayName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayId() string {
	if m != nil {
		return m.DefrayId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayMobile() string {
	if m != nil {
		return m.DefrayMobile
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayEmail() string {
	if m != nil {
		return m.DefrayEmail
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetPayTypeSubNo() string {
	if m != nil {
		return m.PayTypeSubNo
	}
	return ""
}

type CorrespondMerChnRate struct {
	MerchantCode         string   `protobuf:"bytes,1,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	ChannelPayTypesCode  string   `protobuf:"bytes,2,opt,name=ChannelPayTypesCode,proto3" json:"ChannelPayTypesCode,omitempty"`
	ChannelCode          string   `protobuf:"bytes,3,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	PayTypeCode          string   `protobuf:"bytes,4,opt,name=PayTypeCode,proto3" json:"PayTypeCode,omitempty"`
	PayTypeCodeNum       string   `protobuf:"bytes,5,opt,name=PayTypeCodeNum,proto3" json:"PayTypeCodeNum,omitempty"`
	Designation          string   `protobuf:"bytes,6,opt,name=Designation,proto3" json:"Designation,omitempty"`
	DesignationNo        string   `protobuf:"bytes,7,opt,name=DesignationNo,proto3" json:"DesignationNo,omitempty"`
	Fee                  float64  `protobuf:"fixed64,8,opt,name=Fee,proto3" json:"Fee,omitempty"`
	HandlingFee          float64  `protobuf:"fixed64,9,opt,name=HandlingFee,proto3" json:"HandlingFee,omitempty"`
	ChFee                float64  `protobuf:"fixed64,10,opt,name=ChFee,proto3" json:"ChFee,omitempty"`
	ChHandlingFee        float64  `protobuf:"fixed64,11,opt,name=ChHandlingFee,proto3" json:"ChHandlingFee,omitempty"`
	SingleMinCharge      float64  `protobuf:"fixed64,12,opt,name=SingleMinCharge,proto3" json:"SingleMinCharge,omitempty"`
	SingleMaxCharge      float64  `protobuf:"fixed64,13,opt,name=SingleMaxCharge,proto3" json:"SingleMaxCharge,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,14,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	ApiUrl               string   `protobuf:"bytes,15,opt,name=ApiUrl,proto3" json:"ApiUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorrespondMerChnRate) Reset()         { *m = CorrespondMerChnRate{} }
func (m *CorrespondMerChnRate) String() string { return proto.CompactTextString(m) }
func (*CorrespondMerChnRate) ProtoMessage()    {}
func (*CorrespondMerChnRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *CorrespondMerChnRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrespondMerChnRate.Unmarshal(m, b)
}
func (m *CorrespondMerChnRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrespondMerChnRate.Marshal(b, m, deterministic)
}
func (m *CorrespondMerChnRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrespondMerChnRate.Merge(m, src)
}
func (m *CorrespondMerChnRate) XXX_Size() int {
	return xxx_messageInfo_CorrespondMerChnRate.Size(m)
}
func (m *CorrespondMerChnRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrespondMerChnRate.DiscardUnknown(m)
}

var xxx_messageInfo_CorrespondMerChnRate proto.InternalMessageInfo

func (m *CorrespondMerChnRate) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelPayTypesCode() string {
	if m != nil {
		return m.ChannelPayTypesCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCodeNum() string {
	if m != nil {
		return m.PayTypeCodeNum
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignationNo() string {
	if m != nil {
		return m.DesignationNo
	}
	return ""
}

func (m *CorrespondMerChnRate) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetHandlingFee() float64 {
	if m != nil {
		return m.HandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChFee() float64 {
	if m != nil {
		return m.ChFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChHandlingFee() float64 {
	if m != nil {
		return m.ChHandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMinCharge() float64 {
	if m != nil {
		return m.SingleMinCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMaxCharge() float64 {
	if m != nil {
		return m.SingleMaxCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

type PayOrderRequest struct {
	PayOrder             *PayOrder             `protobuf:"bytes,1,opt,name=payOrder,proto3" json:"payOrder,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	OrderNo              string                `protobuf:"bytes,3,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	ChannelOrderNo       string                `protobuf:"bytes,4,opt,name=ChannelOrderNo,proto3" json:"ChannelOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PayOrderRequest) Reset()         { *m = PayOrderRequest{} }
func (m *PayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderRequest) ProtoMessage()    {}
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *PayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderRequest.Unmarshal(m, b)
}
func (m *PayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderRequest.Merge(m, src)
}
func (m *PayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderRequest.Size(m)
}
func (m *PayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderRequest proto.InternalMessageInfo

func (m *PayOrderRequest) GetPayOrder() *PayOrder {
	if m != nil {
		return m.PayOrder
	}
	return nil
}

func (m *PayOrderRequest) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *PayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrderRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

type PayOrderResponse struct {
	PayOrderNo           string   `protobuf:"bytes,1,opt,name=PayOrderNo,proto3" json:"PayOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderResponse) Reset()         { *m = PayOrderResponse{} }
func (m *PayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PayOrderResponse) ProtoMessage()    {}
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *PayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderResponse.Unmarshal(m, b)
}
func (m *PayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderResponse.Marshal(b, m, deterministic)
}
func (m *PayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderResponse.Merge(m, src)
}
func (m *PayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PayOrderResponse.Size(m)
}
func (m *PayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderResponse proto.InternalMessageInfo

func (m *PayOrderResponse) GetPayOrderNo() string {
	if m != nil {
		return m.PayOrderNo
	}
	return ""
}

type PayOrder struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,3,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	PageUrl              string   `protobuf:"bytes,4,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=Sign,proto3" json:"Sign,omitempty"`
	JumpType             string   `protobuf:"bytes,7,opt,name=JumpType,proto3" json:"JumpType,omitempty"`
	LoginType            string   `protobuf:"bytes,8,opt,name=LoginType,proto3" json:"LoginType,omitempty"`
	OrderNo              string   `protobuf:"bytes,9,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	OrderAmount          string   `protobuf:"bytes,10,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	Currency             string   `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayType              string   `protobuf:"bytes,12,opt,name=PayType,proto3" json:"PayType,omitempty"`
	OrderTime            string   `protobuf:"bytes,13,opt,name=OrderTime,proto3" json:"OrderTime,omitempty"`
	OrderName            string   `protobuf:"bytes,14,opt,name=OrderName,proto3" json:"OrderName,omitempty"`
	BankCode             string   `protobuf:"bytes,15,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	Phone                string   `protobuf:"bytes,16,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PayTypeNo            string   `protobuf:"bytes,17,opt,name=PayTypeNo,proto3" json:"PayTypeNo,omitempty"`
	UserId               string   `protobuf:"bytes,18,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MerchantLevel        string   `protobuf:"bytes,19,opt,name=MerchantLevel,proto3" json:"MerchantLevel,omitempty"`
	UserIp               string   `protobuf:"bytes,20,opt,name=UserIp,proto3" json:"UserIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrder) Reset()         { *m = PayOrder{} }
func (m *PayOrder) String() string { return proto.CompactTextString(m) }
func (*PayOrder) ProtoMessage()    {}
func (*PayOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *PayOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrder.Unmarshal(m, b)
}
func (m *PayOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrder.Marshal(b, m, deterministic)
}
func (m *PayOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrder.Merge(m, src)
}
func (m *PayOrder) XXX_Size() int {
	return xxx_messageInfo_PayOrder.Size(m)
}
func (m *PayOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrder proto.InternalMessageInfo

func (m *PayOrder) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *PayOrder) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *PayOrder) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *PayOrder) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *PayOrder) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PayOrder) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayOrder) GetJumpType() string {
	if m != nil {
		return m.JumpType
	}
	return ""
}

func (m *PayOrder) GetLoginType() string {
	if m != nil {
		return m.LoginType
	}
	return ""
}

func (m *PayOrder) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrder) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *PayOrder) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PayOrder) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PayOrder) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *PayOrder) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

func (m *PayOrder) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *PayOrder) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PayOrder) GetPayTypeNo() string {
	if m != nil {
		return m.PayTypeNo
	}
	return ""
}

func (m *PayOrder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PayOrder) GetMerchantLevel() string {
	if m != nil {
		return m.MerchantLevel
	}
	return ""
}

func (m *PayOrder) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

type InternalOrderRequest struct {
	InternalOrder             *InternalOrder             `protobuf:"bytes,1,opt,name=internalOrder,proto3" json:"internalOrder,omitempty"`
	MerchantOrderRateListView *MerchantOrderRateListView `protobuf:"bytes,2,opt,name=merchantOrderRateListView,proto3" json:"merchantOrderRateListView,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *InternalOrderRequest) Reset()         { *m = InternalOrderRequest{} }
func (m *InternalOrderRequest) String() string { return proto.CompactTextString(m) }
func (*InternalOrderRequest) ProtoMessage()    {}
func (*InternalOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *InternalOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrderRequest.Unmarshal(m, b)
}
func (m *InternalOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrderRequest.Marshal(b, m, deterministic)
}
func (m *InternalOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrderRequest.Merge(m, src)
}
func (m *InternalOrderRequest) XXX_Size() int {
	return xxx_messageInfo_InternalOrderRequest.Size(m)
}
func (m *InternalOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrderRequest proto.InternalMessageInfo

func (m *InternalOrderRequest) GetInternalOrder() *InternalOrder {
	if m != nil {
		return m.InternalOrder
	}
	return nil
}

func (m *InternalOrderRequest) GetMerchantOrderRateListView() *MerchantOrderRateListView {
	if m != nil {
		return m.MerchantOrderRateListView
	}
	return nil
}

type InternalOrderResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalOrderResponse) Reset()         { *m = InternalOrderResponse{} }
func (m *InternalOrderResponse) String() string { return proto.CompactTextString(m) }
func (*InternalOrderResponse) ProtoMessage()    {}
func (*InternalOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{8}
}

func (m *InternalOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrderResponse.Unmarshal(m, b)
}
func (m *InternalOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrderResponse.Marshal(b, m, deterministic)
}
func (m *InternalOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrderResponse.Merge(m, src)
}
func (m *InternalOrderResponse) XXX_Size() int {
	return xxx_messageInfo_InternalOrderResponse.Size(m)
}
func (m *InternalOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrderResponse proto.InternalMessageInfo

func (m *InternalOrderResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type InternalOrder struct {
	Imgurl               string   `protobuf:"bytes,1,opt,name=Imgurl,proto3" json:"Imgurl,omitempty"`
	MerchantCode         string   `protobuf:"bytes,2,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	UserAccount          string   `protobuf:"bytes,3,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,4,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,5,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	MerchantAccountName  string   `protobuf:"bytes,6,opt,name=MerchantAccountName,proto3" json:"MerchantAccountName,omitempty"`
	MerchantBankAccount  string   `protobuf:"bytes,7,opt,name=MerchantBankAccount,proto3" json:"MerchantBankAccount,omitempty"`
	MerchantBankCity     string   `protobuf:"bytes,8,opt,name=MerchantBankCity,proto3" json:"MerchantBankCity,omitempty"`
	MerchantBankProvince string   `protobuf:"bytes,9,opt,name=merchantBankProvince,proto3" json:"merchantBankProvince,omitempty"`
	MerchantBankNo       string   `protobuf:"bytes,10,opt,name=MerchantBankNo,proto3" json:"MerchantBankNo,omitempty"`
	MerchantBankName     string   `protobuf:"bytes,11,opt,name=MerchantBankName,proto3" json:"MerchantBankName,omitempty"`
	ChannelBankName      string   `protobuf:"bytes,12,opt,name=ChannelBankName,proto3" json:"ChannelBankName,omitempty"`
	ChannelAccountName   string   `protobuf:"bytes,13,opt,name=ChannelAccountName,proto3" json:"ChannelAccountName,omitempty"`
	ChannelBankAccount   string   `protobuf:"bytes,14,opt,name=ChannelBankAccount,proto3" json:"ChannelBankAccount,omitempty"`
	ChannelBankNo        string   `protobuf:"bytes,15,opt,name=ChannelBankNo,proto3" json:"ChannelBankNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalOrder) Reset()         { *m = InternalOrder{} }
func (m *InternalOrder) String() string { return proto.CompactTextString(m) }
func (*InternalOrder) ProtoMessage()    {}
func (*InternalOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{9}
}

func (m *InternalOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrder.Unmarshal(m, b)
}
func (m *InternalOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrder.Marshal(b, m, deterministic)
}
func (m *InternalOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrder.Merge(m, src)
}
func (m *InternalOrder) XXX_Size() int {
	return xxx_messageInfo_InternalOrder.Size(m)
}
func (m *InternalOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrder.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrder proto.InternalMessageInfo

func (m *InternalOrder) GetImgurl() string {
	if m != nil {
		return m.Imgurl
	}
	return ""
}

func (m *InternalOrder) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *InternalOrder) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *InternalOrder) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *InternalOrder) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *InternalOrder) GetMerchantAccountName() string {
	if m != nil {
		return m.MerchantAccountName
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankAccount() string {
	if m != nil {
		return m.MerchantBankAccount
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankCity() string {
	if m != nil {
		return m.MerchantBankCity
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankProvince() string {
	if m != nil {
		return m.MerchantBankProvince
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankNo() string {
	if m != nil {
		return m.MerchantBankNo
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankName() string {
	if m != nil {
		return m.MerchantBankName
	}
	return ""
}

func (m *InternalOrder) GetChannelBankName() string {
	if m != nil {
		return m.ChannelBankName
	}
	return ""
}

func (m *InternalOrder) GetChannelAccountName() string {
	if m != nil {
		return m.ChannelAccountName
	}
	return ""
}

func (m *InternalOrder) GetChannelBankAccount() string {
	if m != nil {
		return m.ChannelBankAccount
	}
	return ""
}

func (m *InternalOrder) GetChannelBankNo() string {
	if m != nil {
		return m.ChannelBankNo
	}
	return ""
}

type MerchantOrderRateListView struct {
	ChannelPayTypesCode  string   `protobuf:"bytes,1,opt,name=ChannelPayTypesCode,proto3" json:"ChannelPayTypesCode,omitempty"`
	PayTypeCode          string   `protobuf:"bytes,2,opt,name=PayTypeCode,proto3" json:"PayTypeCode,omitempty"`
	PayTypeCodeNum       string   `protobuf:"bytes,3,opt,name=PayTypeCodeNum,proto3" json:"PayTypeCodeNum,omitempty"`
	MerHandlingFee       float64  `protobuf:"fixed64,4,opt,name=MerHandlingFee,proto3" json:"MerHandlingFee,omitempty"`
	MerFee               float64  `protobuf:"fixed64,5,opt,name=MerFee,proto3" json:"MerFee,omitempty"`
	Designation          string   `protobuf:"bytes,6,opt,name=Designation,proto3" json:"Designation,omitempty"`
	DesignationNo        string   `protobuf:"bytes,7,opt,name=DesignationNo,proto3" json:"DesignationNo,omitempty"`
	ChannelCode          string   `protobuf:"bytes,8,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,9,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	MaxInternalCharge    float64  `protobuf:"fixed64,10,opt,name=MaxInternalCharge,proto3" json:"MaxInternalCharge,omitempty"`
	SingleMinCharge      float64  `protobuf:"fixed64,11,opt,name=SingleMinCharge,proto3" json:"SingleMinCharge,omitempty"`
	SingleMaxCharge      float64  `protobuf:"fixed64,12,opt,name=SingleMaxCharge,proto3" json:"SingleMaxCharge,omitempty"`
	MerchantCode         string   `protobuf:"bytes,13,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	MerchnrateStatus     string   `protobuf:"bytes,14,opt,name=MerchnrateStatus,proto3" json:"MerchnrateStatus,omitempty"`
	ChnStatus            string   `protobuf:"bytes,15,opt,name=ChnStatus,proto3" json:"ChnStatus,omitempty"`
	ChnIsProxy           string   `protobuf:"bytes,16,opt,name=ChnIsProxy,proto3" json:"ChnIsProxy,omitempty"`
	CptStatus            string   `protobuf:"bytes,17,opt,name=CptStatus,proto3" json:"CptStatus,omitempty"`
	CptFee               float64  `protobuf:"fixed64,18,opt,name=CptFee,proto3" json:"CptFee,omitempty"`
	CptHandlingFee       float64  `protobuf:"fixed64,19,opt,name=CptHandlingFee,proto3" json:"CptHandlingFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantOrderRateListView) Reset()         { *m = MerchantOrderRateListView{} }
func (m *MerchantOrderRateListView) String() string { return proto.CompactTextString(m) }
func (*MerchantOrderRateListView) ProtoMessage()    {}
func (*MerchantOrderRateListView) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{10}
}

func (m *MerchantOrderRateListView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOrderRateListView.Unmarshal(m, b)
}
func (m *MerchantOrderRateListView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOrderRateListView.Marshal(b, m, deterministic)
}
func (m *MerchantOrderRateListView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOrderRateListView.Merge(m, src)
}
func (m *MerchantOrderRateListView) XXX_Size() int {
	return xxx_messageInfo_MerchantOrderRateListView.Size(m)
}
func (m *MerchantOrderRateListView) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOrderRateListView.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOrderRateListView proto.InternalMessageInfo

func (m *MerchantOrderRateListView) GetChannelPayTypesCode() string {
	if m != nil {
		return m.ChannelPayTypesCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetPayTypeCodeNum() string {
	if m != nil {
		return m.PayTypeCodeNum
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMerHandlingFee() float64 {
	if m != nil {
		return m.MerHandlingFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetMerFee() float64 {
	if m != nil {
		return m.MerFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *MerchantOrderRateListView) GetDesignationNo() string {
	if m != nil {
		return m.DesignationNo
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMaxInternalCharge() float64 {
	if m != nil {
		return m.MaxInternalCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetSingleMinCharge() float64 {
	if m != nil {
		return m.SingleMinCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetSingleMaxCharge() float64 {
	if m != nil {
		return m.SingleMaxCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMerchnrateStatus() string {
	if m != nil {
		return m.MerchnrateStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChnStatus() string {
	if m != nil {
		return m.ChnStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChnIsProxy() string {
	if m != nil {
		return m.ChnIsProxy
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCptStatus() string {
	if m != nil {
		return m.CptStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCptFee() float64 {
	if m != nil {
		return m.CptFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetCptHandlingFee() float64 {
	if m != nil {
		return m.CptHandlingFee
	}
	return 0
}

func init() {
	proto.RegisterType((*ProxyOrderReq_DFB)(nil), "transaction.ProxyOrderReq_DFB")
	proto.RegisterType((*ProxyOrderResp_DFB)(nil), "transaction.ProxyOrderResp_DFB")
	proto.RegisterType((*ProxyPayOrderRequest)(nil), "transaction.ProxyPayOrderRequest")
	proto.RegisterType((*CorrespondMerChnRate)(nil), "transaction.CorrespondMerChnRate")
	proto.RegisterType((*PayOrderRequest)(nil), "transaction.PayOrderRequest")
	proto.RegisterType((*PayOrderResponse)(nil), "transaction.PayOrderResponse")
	proto.RegisterType((*PayOrder)(nil), "transaction.PayOrder")
	proto.RegisterType((*InternalOrderRequest)(nil), "transaction.InternalOrderRequest")
	proto.RegisterType((*InternalOrderResponse)(nil), "transaction.InternalOrderResponse")
	proto.RegisterType((*InternalOrder)(nil), "transaction.InternalOrder")
	proto.RegisterType((*MerchantOrderRateListView)(nil), "transaction.MerchantOrderRateListView")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 1309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x97, 0x63, 0x3b, 0xb1, 0xc7, 0x75, 0xfe, 0x6c, 0x5c, 0x74, 0x8d, 0x4a, 0x49, 0x4f, 0xa8,
	0x8a, 0x10, 0x0a, 0x6d, 0x2a, 0x24, 0x1e, 0x49, 0xae, 0x54, 0x18, 0xc5, 0x26, 0x5c, 0x5a, 0x90,
	0x78, 0x41, 0x1b, 0x7b, 0x6b, 0x9f, 0xb0, 0xf7, 0xae, 0x77, 0xe7, 0x52, 0x7f, 0x17, 0x1e, 0xe0,
	0x83, 0x80, 0xf8, 0x04, 0xbc, 0xf0, 0x71, 0x78, 0x41, 0xb3, 0x7f, 0x7c, 0xb3, 0xe7, 0x73, 0x54,
	0x04, 0x6f, 0x9e, 0xdf, 0xcc, 0xce, 0xcd, 0xee, 0xfd, 0xe6, 0xb7, 0x73, 0x86, 0x83, 0x3c, 0xe5,
	0x32, 0xe3, 0xa3, 0x3c, 0x8a, 0xe5, 0x69, 0x92, 0xc6, 0x79, 0xcc, 0x3a, 0x04, 0xf2, 0x7f, 0xad,
	0xc1, 0xc1, 0x55, 0x1a, 0xbf, 0x5d, 0x7e, 0x9d, 0x8e, 0x45, 0x1a, 0x8a, 0xd7, 0x3f, 0x3c, 0x7b,
	0x7e, 0xc1, 0x9e, 0x42, 0x3d, 0x15, 0xaf, 0xbd, 0xda, 0x71, 0xed, 0xa4, 0x73, 0xf6, 0xf0, 0x94,
	0xe6, 0x50, 0xc1, 0x57, 0x7c, 0x15, 0xbf, 0x10, 0x59, 0x1e, 0x62, 0x34, 0xfb, 0x14, 0x1a, 0x29,
	0xcf, 0x85, 0xb7, 0x55, 0xb1, 0x2a, 0x88, 0xd3, 0x54, 0x64, 0x49, 0x2c, 0xc7, 0x03, 0x91, 0x06,
	0x53, 0x19, 0xf2, 0x5c, 0x84, 0x2a, 0x9c, 0x1d, 0x43, 0xe7, 0x86, 0xcf, 0xb8, 0x1c, 0x89, 0x17,
	0xcb, 0x44, 0x78, 0xf5, 0xe3, 0xda, 0x49, 0x3b, 0xa4, 0x90, 0xff, 0x19, 0x30, 0x5a, 0x62, 0x96,
	0xa8, 0x1a, 0x7d, 0xb8, 0x53, 0xa0, 0xc3, 0x58, 0x15, 0xdb, 0x0e, 0x1d, 0xcc, 0xff, 0xb3, 0x01,
	0xbd, 0xaa, 0x82, 0xd9, 0x03, 0x80, 0xf3, 0xd1, 0x48, 0x64, 0x99, 0x7a, 0xa6, 0x5e, 0x4a, 0x10,
	0xf4, 0x0f, 0x44, 0x3a, 0x9a, 0x72, 0x99, 0xf7, 0xc7, 0x6a, 0x47, 0xed, 0x90, 0x20, 0x8c, 0x41,
	0xe3, 0x3a, 0x9a, 0x48, 0x53, 0xad, 0xfa, 0xcd, 0xee, 0x43, 0x7b, 0x18, 0xe7, 0xd1, 0xab, 0xe5,
	0xcb, 0x74, 0xe6, 0x35, 0x94, 0xa3, 0x00, 0xd8, 0x11, 0xb4, 0x2e, 0xb9, 0x9c, 0x2c, 0xf8, 0x44,
	0x78, 0x4d, 0xe5, 0x5c, 0xd9, 0xcc, 0x83, 0x1d, 0xbb, 0x8b, 0x6d, 0xe5, 0xb2, 0x26, 0x7b, 0x0f,
	0xb6, 0x2f, 0xb8, 0xfc, 0xb1, 0x3f, 0xf6, 0x76, 0x94, 0xc3, 0x58, 0x98, 0x0d, 0x7f, 0x0d, 0xf9,
	0x5c, 0x78, 0x2d, 0x9d, 0xcd, 0xda, 0x78, 0x30, 0xf8, 0xfb, 0x2a, 0x8d, 0xdf, 0x44, 0x72, 0x24,
	0xbc, 0xb6, 0x3e, 0x18, 0x8a, 0xd9, 0xf5, 0x41, 0x94, 0x2f, 0x3d, 0x28, 0xd6, 0xa3, 0x8d, 0x7b,
	0xbf, 0x48, 0xb9, 0x1c, 0x4d, 0x55, 0xf6, 0x8e, 0xde, 0x7b, 0x81, 0xd8, 0x9a, 0x86, 0xb1, 0x77,
	0xa7, 0xa8, 0x69, 0x18, 0xe3, 0x8b, 0x54, 0x65, 0x9f, 0xcf, 0xe3, 0x85, 0xcc, 0xbd, 0xee, 0x71,
	0xed, 0xa4, 0x16, 0x52, 0x08, 0x33, 0x3f, 0x13, 0xaf, 0x52, 0xbe, 0x54, 0x99, 0x77, 0x75, 0xe6,
	0x02, 0xc1, 0xaa, 0xb4, 0xd5, 0x1f, 0x7b, 0x7b, 0xba, 0x2a, 0x6b, 0xe3, 0xae, 0xf4, 0xef, 0x41,
	0x7c, 0x13, 0xcd, 0x84, 0xb7, 0xaf, 0x77, 0x45, 0x31, 0xac, 0x40, 0xdb, 0x5f, 0xcc, 0x79, 0x34,
	0xf3, 0x0e, 0x34, 0x95, 0x08, 0x84, 0x4f, 0x08, 0x16, 0x69, 0x2a, 0xe4, 0x68, 0xe9, 0x31, 0xfd,
	0x04, 0x6b, 0x2b, 0x42, 0xf1, 0x25, 0xbe, 0xfe, 0xeb, 0xc5, 0xcd, 0x30, 0xf6, 0x0e, 0x0d, 0xa1,
	0x08, 0xe6, 0xff, 0xd2, 0x80, 0x5e, 0x15, 0x97, 0x71, 0xb1, 0xa5, 0x47, 0x10, 0x8f, 0x2d, 0xa5,
	0x1c, 0x8c, 0x3d, 0x86, 0xc3, 0x60, 0xca, 0xa5, 0x14, 0x33, 0x93, 0x33, 0x53, 0xa1, 0x9a, 0x5d,
	0x55, 0x2e, 0xdc, 0x90, 0x81, 0x55, 0xa4, 0xe9, 0x0d, 0x02, 0x61, 0x84, 0x59, 0xa1, 0x22, 0x34,
	0xed, 0x28, 0xc4, 0x1e, 0xc1, 0x2e, 0x31, 0x87, 0x8b, 0xb9, 0xa1, 0x5f, 0x09, 0xd5, 0x87, 0x97,
	0x45, 0x13, 0xc9, 0xb1, 0x63, 0x0d, 0x11, 0x29, 0xc4, 0x3e, 0x84, 0x2e, 0x31, 0x87, 0xb1, 0xe1,
	0xa4, 0x0b, 0xb2, 0x7d, 0xa8, 0x3f, 0x17, 0x9a, 0x95, 0xb5, 0x10, 0x7f, 0x62, 0xe6, 0x2f, 0xb9,
	0x1c, 0xcf, 0x22, 0x39, 0x41, 0x4f, 0x5b, 0x13, 0x83, 0x40, 0xac, 0x07, 0xcd, 0x60, 0x8a, 0x3e,
	0x50, 0x3e, 0x6d, 0xe0, 0xf3, 0x82, 0x29, 0x5d, 0xd9, 0x51, 0x5e, 0x17, 0x64, 0x27, 0xb0, 0x77,
	0x1d, 0xc9, 0xc9, 0x4c, 0x0c, 0x22, 0x19, 0x4c, 0x79, 0x3a, 0x11, 0x8a, 0x97, 0xb5, 0xb0, 0x0c,
	0x93, 0x48, 0xfe, 0xd6, 0x44, 0x76, 0x9d, 0x48, 0x0b, 0xe3, 0xdb, 0xb4, 0xb4, 0x50, 0xc7, 0xaa,
	0xa9, 0xea, 0x60, 0xd8, 0x06, 0xe7, 0x49, 0x84, 0xbd, 0xae, 0xa9, 0x6a, 0x2c, 0xff, 0xb7, 0x1a,
	0xec, 0x95, 0xe5, 0xe6, 0x09, 0xb4, 0x12, 0x03, 0x19, 0x51, 0xbd, 0xeb, 0x8a, 0xaa, 0x8d, 0x5f,
	0x85, 0xa1, 0x9a, 0x86, 0xff, 0x4e, 0x4d, 0x15, 0x0f, 0x89, 0x94, 0xd4, 0x5d, 0x29, 0x79, 0x04,
	0xbb, 0x86, 0x38, 0x36, 0x40, 0x93, 0xa5, 0x84, 0xfa, 0x67, 0xb0, 0x5f, 0x94, 0x8f, 0x0f, 0xc9,
	0x94, 0x1c, 0x5a, 0x6c, 0xa5, 0xb4, 0x04, 0xf1, 0xff, 0x68, 0x40, 0xcb, 0x9a, 0xff, 0x59, 0x5b,
	0x1d, 0x1d, 0xad, 0x97, 0x75, 0xd4, 0x83, 0x9d, 0x2b, 0x3e, 0x11, 0x85, 0xc6, 0x5a, 0xf3, 0x56,
	0x85, 0xb5, 0x7a, 0xbd, 0x4d, 0xf4, 0xfa, 0x08, 0x5a, 0x5f, 0x2d, 0xe6, 0x89, 0xaa, 0x52, 0x33,
	0x79, 0x65, 0x63, 0x0d, 0x97, 0xf1, 0x24, 0x92, 0xca, 0xa9, 0x05, 0xb6, 0x00, 0xe8, 0x21, 0xb7,
	0xdd, 0x43, 0x2e, 0x69, 0xa0, 0x96, 0x56, 0x47, 0x03, 0xa9, 0x02, 0x75, 0x4a, 0x0a, 0xa4, 0xf6,
	0xa6, 0x9a, 0xd2, 0x48, 0xab, 0x35, 0xb1, 0x1e, 0x95, 0xe4, 0x45, 0x34, 0xd7, 0xa4, 0x6d, 0x87,
	0x05, 0xb0, 0xf2, 0x12, 0x59, 0x2d, 0x80, 0x95, 0xd6, 0x23, 0x91, 0xf7, 0x88, 0xd6, 0x23, 0x89,
	0x7b, 0xd0, 0xbc, 0x9a, 0xc6, 0xd2, 0xca, 0xa9, 0x36, 0x30, 0x9f, 0x79, 0xf0, 0x30, 0x36, 0x2a,
	0x5a, 0x00, 0x48, 0xfc, 0x97, 0x99, 0x48, 0xfb, 0x63, 0xa3, 0xa0, 0xc6, 0xc2, 0x76, 0xb5, 0x6f,
	0xf1, 0x52, 0xbc, 0x11, 0x33, 0x23, 0xa0, 0x2e, 0xb8, 0x5a, 0x9d, 0x78, 0x3d, 0xb2, 0x3a, 0xf1,
	0x7f, 0xaf, 0x41, 0xaf, 0x2f, 0x73, 0x91, 0x4a, 0x3e, 0x73, 0x7a, 0xe7, 0x73, 0xe8, 0x46, 0x14,
	0x37, 0x0d, 0x74, 0xe4, 0x74, 0x84, 0xbb, 0xd2, 0x5d, 0xc0, 0xc6, 0x70, 0x6f, 0x6e, 0x6a, 0xd0,
	0x7e, 0x9e, 0x8b, 0xcb, 0x28, 0xcb, 0xbf, 0x8d, 0xc4, 0x4f, 0xa6, 0xbf, 0x1e, 0x39, 0xd9, 0x06,
	0x9b, 0xa2, 0xc3, 0xcd, 0x89, 0xfc, 0x27, 0x70, 0xb7, 0x54, 0xbf, 0x69, 0x1e, 0x0f, 0x76, 0x62,
	0xa7, 0x73, 0xac, 0xe9, 0xff, 0xdd, 0x80, 0xae, 0xb3, 0x06, 0x4f, 0xa7, 0x3f, 0x9f, 0x2c, 0xd2,
	0x99, 0x09, 0x35, 0xd6, 0xda, 0xf5, 0xb2, 0x55, 0x71, 0xbd, 0x1c, 0x43, 0x07, 0xcf, 0xf2, 0x7c,
	0x34, 0x52, 0xdc, 0x33, 0x97, 0x05, 0x81, 0xca, 0xec, 0x6c, 0xac, 0xdf, 0xd0, 0x65, 0xe1, 0x6b,
	0x56, 0x08, 0xdf, 0x63, 0x38, 0xb4, 0xcf, 0x35, 0x89, 0x15, 0xef, 0x74, 0x6b, 0x55, 0xb9, 0xe8,
	0x0a, 0x64, 0x9e, 0xad, 0x70, 0xc7, 0x5d, 0x41, 0x5c, 0xec, 0x23, 0xd8, 0xa7, 0xb0, 0x9a, 0x53,
	0x74, 0x1b, 0xae, 0xe1, 0xec, 0x0c, 0x7a, 0x73, 0x82, 0x95, 0xe6, 0x9e, 0x4a, 0x1f, 0x8a, 0x21,
	0xcd, 0x33, 0x8c, 0x4d, 0xab, 0x96, 0xd0, 0x72, 0x1d, 0x64, 0x22, 0x5a, 0xc3, 0xf1, 0x7a, 0x31,
	0x52, 0xba, 0x0a, 0xd5, 0x5d, 0x5c, 0x86, 0xd9, 0x29, 0x30, 0x03, 0xd1, 0x03, 0xd4, 0x6d, 0x5d,
	0xe1, 0x21, 0xf1, 0xf4, 0xf8, 0x76, 0x9d, 0x78, 0x7a, 0x7a, 0xea, 0xe2, 0x2c, 0x1e, 0x19, 0x9b,
	0xb6, 0x77, 0x41, 0xff, 0xaf, 0x26, 0xdc, 0xdb, 0xc8, 0xf4, 0x4d, 0xc3, 0x4a, 0xed, 0xd6, 0x61,
	0x85, 0x8e, 0x22, 0x5b, 0xef, 0x32, 0x8a, 0xd4, 0x2b, 0x47, 0x11, 0xfd, 0x76, 0xe8, 0xcd, 0xaf,
	0xa9, 0x5a, 0x42, 0xb1, 0x5b, 0x06, 0x22, 0x45, 0x7f, 0x53, 0xf9, 0x8d, 0xf5, 0xbf, 0x8d, 0x32,
	0xa5, 0xf1, 0xab, 0xb5, 0x3e, 0x7e, 0x95, 0xfb, 0xa5, 0x5d, 0xd1, 0x2f, 0x1f, 0xc3, 0xc1, 0x80,
	0xbf, 0xb5, 0x7d, 0x6e, 0x06, 0x0f, 0x3d, 0xe8, 0xac, 0x3b, 0xaa, 0xc6, 0x99, 0xce, 0x3b, 0x8f,
	0x33, 0x77, 0x36, 0x8e, 0x33, 0x8e, 0x7a, 0x74, 0x2b, 0xd4, 0xc3, 0x32, 0x5d, 0xe2, 0x47, 0xd9,
	0x75, 0xce, 0xf3, 0x45, 0x66, 0x18, 0xb6, 0x86, 0xe3, 0xfd, 0x10, 0x4c, 0xa5, 0x09, 0xd2, 0xdc,
	0x2a, 0x00, 0xbc, 0xdf, 0x83, 0xa9, 0xec, 0x67, 0xea, 0xc3, 0xcb, 0x5c, 0x2c, 0x04, 0x51, 0xab,
	0x93, 0xdc, 0xac, 0x36, 0xb7, 0xcb, 0x0a, 0xc0, 0x77, 0x1a, 0x24, 0x39, 0xbe, 0x53, 0xa6, 0xdf,
	0xa9, 0xb6, 0xd4, 0xf8, 0x92, 0xe4, 0x94, 0x13, 0x87, 0x9a, 0x13, 0x2e, 0x7a, 0xf6, 0xf3, 0x16,
	0x74, 0x5e, 0x14, 0x5a, 0xce, 0xbe, 0x33, 0x5f, 0x80, 0xfa, 0xb6, 0x4c, 0xb9, 0x34, 0xf8, 0x83,
	0xf5, 0xaf, 0x5a, 0xfa, 0x09, 0x7c, 0xf4, 0xc1, 0x46, 0xbf, 0xf9, 0xfe, 0xfc, 0x06, 0x98, 0x1d,
	0x79, 0x48, 0xda, 0xfb, 0xd5, 0x73, 0x9d, 0xbe, 0xcb, 0x8e, 0xde, 0xdf, 0xe0, 0x35, 0x37, 0x05,
	0x07, 0xcf, 0xb9, 0x0e, 0xe8, 0x3e, 0x1e, 0xde, 0x72, 0xdf, 0x99, 0xec, 0xfe, 0x6d, 0x21, 0xfa,
	0x11, 0x17, 0x7b, 0xdf, 0x77, 0x4f, 0x3f, 0x21, 0x61, 0x37, 0xdb, 0xea, 0x4f, 0x81, 0xa7, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x60, 0xe9, 0xc4, 0x7c, 0x29, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	ProxyOrderTranaction(ctx context.Context, in *ProxyOrderReq_DFB, opts ...grpc.CallOption) (*ProxyOrderResp_DFB, error)
	PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error)
	InternalOrderTransaction(ctx context.Context, in *InternalOrderRequest, opts ...grpc.CallOption) (*InternalOrderResponse, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) ProxyOrderTranaction(ctx context.Context, in *ProxyOrderReq_DFB, opts ...grpc.CallOption) (*ProxyOrderResp_DFB, error) {
	out := new(ProxyOrderResp_DFB)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/ProxyOrderTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error) {
	out := new(PayOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/PayOrderTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) InternalOrderTransaction(ctx context.Context, in *InternalOrderRequest, opts ...grpc.CallOption) (*InternalOrderResponse, error) {
	out := new(InternalOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/InternalOrderTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	ProxyOrderTranaction(context.Context, *ProxyOrderReq_DFB) (*ProxyOrderResp_DFB, error)
	PayOrderTranaction(context.Context, *PayOrderRequest) (*PayOrderResponse, error)
	InternalOrderTransaction(context.Context, *InternalOrderRequest) (*InternalOrderResponse, error)
}

// UnimplementedTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (*UnimplementedTransactionServer) ProxyOrderTranaction(ctx context.Context, req *ProxyOrderReq_DFB) (*ProxyOrderResp_DFB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyOrderTranaction not implemented")
}
func (*UnimplementedTransactionServer) PayOrderTranaction(ctx context.Context, req *PayOrderRequest) (*PayOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrderTranaction not implemented")
}
func (*UnimplementedTransactionServer) InternalOrderTransaction(ctx context.Context, req *InternalOrderRequest) (*InternalOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalOrderTransaction not implemented")
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_ProxyOrderTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyOrderReq_DFB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).ProxyOrderTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/ProxyOrderTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).ProxyOrderTranaction(ctx, req.(*ProxyOrderReq_DFB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_PayOrderTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).PayOrderTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/PayOrderTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).PayOrderTranaction(ctx, req.(*PayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_InternalOrderTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).InternalOrderTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/InternalOrderTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).InternalOrderTransaction(ctx, req.(*InternalOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyOrderTranaction",
			Handler:    _Transaction_ProxyOrderTranaction_Handler,
		},
		{
			MethodName: "PayOrderTranaction",
			Handler:    _Transaction_PayOrderTranaction_Handler,
		},
		{
			MethodName: "InternalOrderTransaction",
			Handler:    _Transaction_InternalOrderTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
