// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyOrderRequest struct {
	Req                  *ProxyPayOrderRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	BalanceType          string                `protobuf:"bytes,3,opt,name=balanceType,proto3" json:"balanceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProxyOrderRequest) Reset()         { *m = ProxyOrderRequest{} }
func (m *ProxyOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderRequest) ProtoMessage()    {}
func (*ProxyOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *ProxyOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderRequest.Unmarshal(m, b)
}
func (m *ProxyOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderRequest.Marshal(b, m, deterministic)
}
func (m *ProxyOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderRequest.Merge(m, src)
}
func (m *ProxyOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderRequest.Size(m)
}
func (m *ProxyOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderRequest proto.InternalMessageInfo

func (m *ProxyOrderRequest) GetReq() *ProxyPayOrderRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ProxyOrderRequest) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *ProxyOrderRequest) GetBalanceType() string {
	if m != nil {
		return m.BalanceType
	}
	return ""
}

type ProxyOrderResponse struct {
	ProxyOrderNo         string   `protobuf:"bytes,1,opt,name=ProxyOrderNo,proto3" json:"ProxyOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyOrderResponse) Reset()         { *m = ProxyOrderResponse{} }
func (m *ProxyOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderResponse) ProtoMessage()    {}
func (*ProxyOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ProxyOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderResponse.Unmarshal(m, b)
}
func (m *ProxyOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderResponse.Marshal(b, m, deterministic)
}
func (m *ProxyOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderResponse.Merge(m, src)
}
func (m *ProxyOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderResponse.Size(m)
}
func (m *ProxyOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderResponse proto.InternalMessageInfo

func (m *ProxyOrderResponse) GetProxyOrderNo() string {
	if m != nil {
		return m.ProxyOrderNo
	}
	return ""
}

type ProxyOrderResp_XFB struct {
	ProxyOrderNo         string   `protobuf:"bytes,1,opt,name=ProxyOrderNo,proto3" json:"ProxyOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyOrderResp_XFB) Reset()         { *m = ProxyOrderResp_XFB{} }
func (m *ProxyOrderResp_XFB) String() string { return proto.CompactTextString(m) }
func (*ProxyOrderResp_XFB) ProtoMessage()    {}
func (*ProxyOrderResp_XFB) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *ProxyOrderResp_XFB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyOrderResp_XFB.Unmarshal(m, b)
}
func (m *ProxyOrderResp_XFB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyOrderResp_XFB.Marshal(b, m, deterministic)
}
func (m *ProxyOrderResp_XFB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyOrderResp_XFB.Merge(m, src)
}
func (m *ProxyOrderResp_XFB) XXX_Size() int {
	return xxx_messageInfo_ProxyOrderResp_XFB.Size(m)
}
func (m *ProxyOrderResp_XFB) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyOrderResp_XFB.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyOrderResp_XFB proto.InternalMessageInfo

func (m *ProxyOrderResp_XFB) GetProxyOrderNo() string {
	if m != nil {
		return m.ProxyOrderNo
	}
	return ""
}

type ProxyPayOrderRequest struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	OrderNo              string   `protobuf:"bytes,6,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	BankId               string   `protobuf:"bytes,7,opt,name=BankId,proto3" json:"BankId,omitempty"`
	BankName             string   `protobuf:"bytes,8,opt,name=BankName,proto3" json:"BankName,omitempty"`
	BankProvince         string   `protobuf:"bytes,9,opt,name=BankProvince,proto3" json:"BankProvince,omitempty"`
	BankCity             string   `protobuf:"bytes,10,opt,name=BankCity,proto3" json:"BankCity,omitempty"`
	BranchName           string   `protobuf:"bytes,11,opt,name=BranchName,proto3" json:"BranchName,omitempty"`
	BankNo               string   `protobuf:"bytes,12,opt,name=BankNo,proto3" json:"BankNo,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,13,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	DefrayName           string   `protobuf:"bytes,14,opt,name=DefrayName,proto3" json:"DefrayName,omitempty"`
	DefrayId             string   `protobuf:"bytes,15,opt,name=DefrayId,proto3" json:"DefrayId,omitempty"`
	DefrayMobile         string   `protobuf:"bytes,16,opt,name=DefrayMobile,proto3" json:"DefrayMobile,omitempty"`
	DefrayEmail          string   `protobuf:"bytes,17,opt,name=DefrayEmail,proto3" json:"DefrayEmail,omitempty"`
	Currency             string   `protobuf:"bytes,18,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayTypeSubNo         string   `protobuf:"bytes,19,opt,name=PayTypeSubNo,proto3" json:"PayTypeSubNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyPayOrderRequest) Reset()         { *m = ProxyPayOrderRequest{} }
func (m *ProxyPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyPayOrderRequest) ProtoMessage()    {}
func (*ProxyPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *ProxyPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyPayOrderRequest.Unmarshal(m, b)
}
func (m *ProxyPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *ProxyPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyPayOrderRequest.Merge(m, src)
}
func (m *ProxyPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyPayOrderRequest.Size(m)
}
func (m *ProxyPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyPayOrderRequest proto.InternalMessageInfo

func (m *ProxyPayOrderRequest) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankId() string {
	if m != nil {
		return m.BankId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankProvince() string {
	if m != nil {
		return m.BankProvince
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankCity() string {
	if m != nil {
		return m.BankCity
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetBankNo() string {
	if m != nil {
		return m.BankNo
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *ProxyPayOrderRequest) GetDefrayName() string {
	if m != nil {
		return m.DefrayName
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayId() string {
	if m != nil {
		return m.DefrayId
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayMobile() string {
	if m != nil {
		return m.DefrayMobile
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetDefrayEmail() string {
	if m != nil {
		return m.DefrayEmail
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *ProxyPayOrderRequest) GetPayTypeSubNo() string {
	if m != nil {
		return m.PayTypeSubNo
	}
	return ""
}

type CorrespondMerChnRate struct {
	MerchantCode         string   `protobuf:"bytes,1,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	ChannelPayTypesCode  string   `protobuf:"bytes,2,opt,name=ChannelPayTypesCode,proto3" json:"ChannelPayTypesCode,omitempty"`
	ChannelCode          string   `protobuf:"bytes,3,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	PayTypeCode          string   `protobuf:"bytes,4,opt,name=PayTypeCode,proto3" json:"PayTypeCode,omitempty"`
	PayTypeCodeNum       string   `protobuf:"bytes,5,opt,name=PayTypeCodeNum,proto3" json:"PayTypeCodeNum,omitempty"`
	Designation          string   `protobuf:"bytes,6,opt,name=Designation,proto3" json:"Designation,omitempty"`
	DesignationNo        string   `protobuf:"bytes,7,opt,name=DesignationNo,proto3" json:"DesignationNo,omitempty"`
	Fee                  float64  `protobuf:"fixed64,8,opt,name=Fee,proto3" json:"Fee,omitempty"`
	HandlingFee          float64  `protobuf:"fixed64,9,opt,name=HandlingFee,proto3" json:"HandlingFee,omitempty"`
	ChFee                float64  `protobuf:"fixed64,10,opt,name=ChFee,proto3" json:"ChFee,omitempty"`
	ChHandlingFee        float64  `protobuf:"fixed64,11,opt,name=ChHandlingFee,proto3" json:"ChHandlingFee,omitempty"`
	SingleMinCharge      float64  `protobuf:"fixed64,12,opt,name=SingleMinCharge,proto3" json:"SingleMinCharge,omitempty"`
	SingleMaxCharge      float64  `protobuf:"fixed64,13,opt,name=SingleMaxCharge,proto3" json:"SingleMaxCharge,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,14,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	ApiUrl               string   `protobuf:"bytes,15,opt,name=ApiUrl,proto3" json:"ApiUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorrespondMerChnRate) Reset()         { *m = CorrespondMerChnRate{} }
func (m *CorrespondMerChnRate) String() string { return proto.CompactTextString(m) }
func (*CorrespondMerChnRate) ProtoMessage()    {}
func (*CorrespondMerChnRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *CorrespondMerChnRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrespondMerChnRate.Unmarshal(m, b)
}
func (m *CorrespondMerChnRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrespondMerChnRate.Marshal(b, m, deterministic)
}
func (m *CorrespondMerChnRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrespondMerChnRate.Merge(m, src)
}
func (m *CorrespondMerChnRate) XXX_Size() int {
	return xxx_messageInfo_CorrespondMerChnRate.Size(m)
}
func (m *CorrespondMerChnRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrespondMerChnRate.DiscardUnknown(m)
}

var xxx_messageInfo_CorrespondMerChnRate proto.InternalMessageInfo

func (m *CorrespondMerChnRate) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelPayTypesCode() string {
	if m != nil {
		return m.ChannelPayTypesCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetPayTypeCodeNum() string {
	if m != nil {
		return m.PayTypeCodeNum
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *CorrespondMerChnRate) GetDesignationNo() string {
	if m != nil {
		return m.DesignationNo
	}
	return ""
}

func (m *CorrespondMerChnRate) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetHandlingFee() float64 {
	if m != nil {
		return m.HandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChFee() float64 {
	if m != nil {
		return m.ChFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetChHandlingFee() float64 {
	if m != nil {
		return m.ChHandlingFee
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMinCharge() float64 {
	if m != nil {
		return m.SingleMinCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetSingleMaxCharge() float64 {
	if m != nil {
		return m.SingleMaxCharge
	}
	return 0
}

func (m *CorrespondMerChnRate) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CorrespondMerChnRate) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

type PayOrderRequest struct {
	PayOrder             *PayOrder             `protobuf:"bytes,1,opt,name=payOrder,proto3" json:"payOrder,omitempty"`
	Rate                 *CorrespondMerChnRate `protobuf:"bytes,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	OrderNo              string                `protobuf:"bytes,3,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	ChannelOrderNo       string                `protobuf:"bytes,4,opt,name=ChannelOrderNo,proto3" json:"ChannelOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PayOrderRequest) Reset()         { *m = PayOrderRequest{} }
func (m *PayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderRequest) ProtoMessage()    {}
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *PayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderRequest.Unmarshal(m, b)
}
func (m *PayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderRequest.Merge(m, src)
}
func (m *PayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderRequest.Size(m)
}
func (m *PayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderRequest proto.InternalMessageInfo

func (m *PayOrderRequest) GetPayOrder() *PayOrder {
	if m != nil {
		return m.PayOrder
	}
	return nil
}

func (m *PayOrderRequest) GetRate() *CorrespondMerChnRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *PayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrderRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

type PayOrderResponse struct {
	PayOrderNo           string   `protobuf:"bytes,1,opt,name=PayOrderNo,proto3" json:"PayOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderResponse) Reset()         { *m = PayOrderResponse{} }
func (m *PayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PayOrderResponse) ProtoMessage()    {}
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *PayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderResponse.Unmarshal(m, b)
}
func (m *PayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderResponse.Marshal(b, m, deterministic)
}
func (m *PayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderResponse.Merge(m, src)
}
func (m *PayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PayOrderResponse.Size(m)
}
func (m *PayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderResponse proto.InternalMessageInfo

func (m *PayOrderResponse) GetPayOrderNo() string {
	if m != nil {
		return m.PayOrderNo
	}
	return ""
}

type PayOrder struct {
	AccessType           string   `protobuf:"bytes,1,opt,name=AccessType,proto3" json:"AccessType,omitempty"`
	MerchantId           string   `protobuf:"bytes,2,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,3,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	PageUrl              string   `protobuf:"bytes,4,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=Sign,proto3" json:"Sign,omitempty"`
	JumpType             string   `protobuf:"bytes,7,opt,name=JumpType,proto3" json:"JumpType,omitempty"`
	LoginType            string   `protobuf:"bytes,8,opt,name=LoginType,proto3" json:"LoginType,omitempty"`
	OrderNo              string   `protobuf:"bytes,9,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	OrderAmount          string   `protobuf:"bytes,10,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	Currency             string   `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PayType              string   `protobuf:"bytes,12,opt,name=PayType,proto3" json:"PayType,omitempty"`
	OrderTime            string   `protobuf:"bytes,13,opt,name=OrderTime,proto3" json:"OrderTime,omitempty"`
	OrderName            string   `protobuf:"bytes,14,opt,name=OrderName,proto3" json:"OrderName,omitempty"`
	BankCode             string   `protobuf:"bytes,15,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	Phone                string   `protobuf:"bytes,16,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PayTypeNo            string   `protobuf:"bytes,17,opt,name=PayTypeNo,proto3" json:"PayTypeNo,omitempty"`
	UserId               string   `protobuf:"bytes,18,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MerchantLevel        string   `protobuf:"bytes,19,opt,name=MerchantLevel,proto3" json:"MerchantLevel,omitempty"`
	UserIp               string   `protobuf:"bytes,20,opt,name=UserIp,proto3" json:"UserIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrder) Reset()         { *m = PayOrder{} }
func (m *PayOrder) String() string { return proto.CompactTextString(m) }
func (*PayOrder) ProtoMessage()    {}
func (*PayOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *PayOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrder.Unmarshal(m, b)
}
func (m *PayOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrder.Marshal(b, m, deterministic)
}
func (m *PayOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrder.Merge(m, src)
}
func (m *PayOrder) XXX_Size() int {
	return xxx_messageInfo_PayOrder.Size(m)
}
func (m *PayOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrder proto.InternalMessageInfo

func (m *PayOrder) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *PayOrder) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *PayOrder) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *PayOrder) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *PayOrder) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PayOrder) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayOrder) GetJumpType() string {
	if m != nil {
		return m.JumpType
	}
	return ""
}

func (m *PayOrder) GetLoginType() string {
	if m != nil {
		return m.LoginType
	}
	return ""
}

func (m *PayOrder) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayOrder) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *PayOrder) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PayOrder) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PayOrder) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *PayOrder) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

func (m *PayOrder) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *PayOrder) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PayOrder) GetPayTypeNo() string {
	if m != nil {
		return m.PayTypeNo
	}
	return ""
}

func (m *PayOrder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PayOrder) GetMerchantLevel() string {
	if m != nil {
		return m.MerchantLevel
	}
	return ""
}

func (m *PayOrder) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

type InternalOrderRequest struct {
	InternalOrder             *InternalOrder             `protobuf:"bytes,1,opt,name=internalOrder,proto3" json:"internalOrder,omitempty"`
	MerchantOrderRateListView *MerchantOrderRateListView `protobuf:"bytes,2,opt,name=merchantOrderRateListView,proto3" json:"merchantOrderRateListView,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *InternalOrderRequest) Reset()         { *m = InternalOrderRequest{} }
func (m *InternalOrderRequest) String() string { return proto.CompactTextString(m) }
func (*InternalOrderRequest) ProtoMessage()    {}
func (*InternalOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{8}
}

func (m *InternalOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrderRequest.Unmarshal(m, b)
}
func (m *InternalOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrderRequest.Marshal(b, m, deterministic)
}
func (m *InternalOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrderRequest.Merge(m, src)
}
func (m *InternalOrderRequest) XXX_Size() int {
	return xxx_messageInfo_InternalOrderRequest.Size(m)
}
func (m *InternalOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrderRequest proto.InternalMessageInfo

func (m *InternalOrderRequest) GetInternalOrder() *InternalOrder {
	if m != nil {
		return m.InternalOrder
	}
	return nil
}

func (m *InternalOrderRequest) GetMerchantOrderRateListView() *MerchantOrderRateListView {
	if m != nil {
		return m.MerchantOrderRateListView
	}
	return nil
}

type InternalOrderResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalOrderResponse) Reset()         { *m = InternalOrderResponse{} }
func (m *InternalOrderResponse) String() string { return proto.CompactTextString(m) }
func (*InternalOrderResponse) ProtoMessage()    {}
func (*InternalOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{9}
}

func (m *InternalOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrderResponse.Unmarshal(m, b)
}
func (m *InternalOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrderResponse.Marshal(b, m, deterministic)
}
func (m *InternalOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrderResponse.Merge(m, src)
}
func (m *InternalOrderResponse) XXX_Size() int {
	return xxx_messageInfo_InternalOrderResponse.Size(m)
}
func (m *InternalOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrderResponse proto.InternalMessageInfo

func (m *InternalOrderResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type InternalOrder struct {
	Imgurl               string   `protobuf:"bytes,1,opt,name=Imgurl,proto3" json:"Imgurl,omitempty"`
	MerchantCode         string   `protobuf:"bytes,2,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	UserAccount          string   `protobuf:"bytes,3,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,4,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,5,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	MerchantAccountName  string   `protobuf:"bytes,6,opt,name=MerchantAccountName,proto3" json:"MerchantAccountName,omitempty"`
	MerchantBankAccount  string   `protobuf:"bytes,7,opt,name=MerchantBankAccount,proto3" json:"MerchantBankAccount,omitempty"`
	MerchantBankCity     string   `protobuf:"bytes,8,opt,name=MerchantBankCity,proto3" json:"MerchantBankCity,omitempty"`
	MerchantBankProvince string   `protobuf:"bytes,9,opt,name=merchantBankProvince,proto3" json:"merchantBankProvince,omitempty"`
	MerchantBankNo       string   `protobuf:"bytes,10,opt,name=MerchantBankNo,proto3" json:"MerchantBankNo,omitempty"`
	MerchantBankName     string   `protobuf:"bytes,11,opt,name=MerchantBankName,proto3" json:"MerchantBankName,omitempty"`
	ChannelBankName      string   `protobuf:"bytes,12,opt,name=ChannelBankName,proto3" json:"ChannelBankName,omitempty"`
	ChannelAccountName   string   `protobuf:"bytes,13,opt,name=ChannelAccountName,proto3" json:"ChannelAccountName,omitempty"`
	ChannelBankAccount   string   `protobuf:"bytes,14,opt,name=ChannelBankAccount,proto3" json:"ChannelBankAccount,omitempty"`
	ChannelBankNo        string   `protobuf:"bytes,15,opt,name=ChannelBankNo,proto3" json:"ChannelBankNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalOrder) Reset()         { *m = InternalOrder{} }
func (m *InternalOrder) String() string { return proto.CompactTextString(m) }
func (*InternalOrder) ProtoMessage()    {}
func (*InternalOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{10}
}

func (m *InternalOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalOrder.Unmarshal(m, b)
}
func (m *InternalOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalOrder.Marshal(b, m, deterministic)
}
func (m *InternalOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalOrder.Merge(m, src)
}
func (m *InternalOrder) XXX_Size() int {
	return xxx_messageInfo_InternalOrder.Size(m)
}
func (m *InternalOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalOrder.DiscardUnknown(m)
}

var xxx_messageInfo_InternalOrder proto.InternalMessageInfo

func (m *InternalOrder) GetImgurl() string {
	if m != nil {
		return m.Imgurl
	}
	return ""
}

func (m *InternalOrder) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *InternalOrder) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *InternalOrder) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *InternalOrder) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *InternalOrder) GetMerchantAccountName() string {
	if m != nil {
		return m.MerchantAccountName
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankAccount() string {
	if m != nil {
		return m.MerchantBankAccount
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankCity() string {
	if m != nil {
		return m.MerchantBankCity
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankProvince() string {
	if m != nil {
		return m.MerchantBankProvince
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankNo() string {
	if m != nil {
		return m.MerchantBankNo
	}
	return ""
}

func (m *InternalOrder) GetMerchantBankName() string {
	if m != nil {
		return m.MerchantBankName
	}
	return ""
}

func (m *InternalOrder) GetChannelBankName() string {
	if m != nil {
		return m.ChannelBankName
	}
	return ""
}

func (m *InternalOrder) GetChannelAccountName() string {
	if m != nil {
		return m.ChannelAccountName
	}
	return ""
}

func (m *InternalOrder) GetChannelBankAccount() string {
	if m != nil {
		return m.ChannelBankAccount
	}
	return ""
}

func (m *InternalOrder) GetChannelBankNo() string {
	if m != nil {
		return m.ChannelBankNo
	}
	return ""
}

type MerchantOrderRateListView struct {
	ChannelPayTypesCode  string   `protobuf:"bytes,1,opt,name=ChannelPayTypesCode,proto3" json:"ChannelPayTypesCode,omitempty"`
	PayTypeCode          string   `protobuf:"bytes,2,opt,name=PayTypeCode,proto3" json:"PayTypeCode,omitempty"`
	PayTypeCodeNum       string   `protobuf:"bytes,3,opt,name=PayTypeCodeNum,proto3" json:"PayTypeCodeNum,omitempty"`
	MerHandlingFee       float64  `protobuf:"fixed64,4,opt,name=MerHandlingFee,proto3" json:"MerHandlingFee,omitempty"`
	MerFee               float64  `protobuf:"fixed64,5,opt,name=MerFee,proto3" json:"MerFee,omitempty"`
	Designation          string   `protobuf:"bytes,6,opt,name=Designation,proto3" json:"Designation,omitempty"`
	DesignationNo        string   `protobuf:"bytes,7,opt,name=DesignationNo,proto3" json:"DesignationNo,omitempty"`
	ChannelCode          string   `protobuf:"bytes,8,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,9,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	MaxInternalCharge    float64  `protobuf:"fixed64,10,opt,name=MaxInternalCharge,proto3" json:"MaxInternalCharge,omitempty"`
	SingleMinCharge      float64  `protobuf:"fixed64,11,opt,name=SingleMinCharge,proto3" json:"SingleMinCharge,omitempty"`
	SingleMaxCharge      float64  `protobuf:"fixed64,12,opt,name=SingleMaxCharge,proto3" json:"SingleMaxCharge,omitempty"`
	MerchantCode         string   `protobuf:"bytes,13,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	MerchnrateStatus     string   `protobuf:"bytes,14,opt,name=MerchnrateStatus,proto3" json:"MerchnrateStatus,omitempty"`
	ChnStatus            string   `protobuf:"bytes,15,opt,name=ChnStatus,proto3" json:"ChnStatus,omitempty"`
	ChnIsProxy           string   `protobuf:"bytes,16,opt,name=ChnIsProxy,proto3" json:"ChnIsProxy,omitempty"`
	CptStatus            string   `protobuf:"bytes,17,opt,name=CptStatus,proto3" json:"CptStatus,omitempty"`
	CptFee               float64  `protobuf:"fixed64,18,opt,name=CptFee,proto3" json:"CptFee,omitempty"`
	CptHandlingFee       float64  `protobuf:"fixed64,19,opt,name=CptHandlingFee,proto3" json:"CptHandlingFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantOrderRateListView) Reset()         { *m = MerchantOrderRateListView{} }
func (m *MerchantOrderRateListView) String() string { return proto.CompactTextString(m) }
func (*MerchantOrderRateListView) ProtoMessage()    {}
func (*MerchantOrderRateListView) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{11}
}

func (m *MerchantOrderRateListView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOrderRateListView.Unmarshal(m, b)
}
func (m *MerchantOrderRateListView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOrderRateListView.Marshal(b, m, deterministic)
}
func (m *MerchantOrderRateListView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOrderRateListView.Merge(m, src)
}
func (m *MerchantOrderRateListView) XXX_Size() int {
	return xxx_messageInfo_MerchantOrderRateListView.Size(m)
}
func (m *MerchantOrderRateListView) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOrderRateListView.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOrderRateListView proto.InternalMessageInfo

func (m *MerchantOrderRateListView) GetChannelPayTypesCode() string {
	if m != nil {
		return m.ChannelPayTypesCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetPayTypeCodeNum() string {
	if m != nil {
		return m.PayTypeCodeNum
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMerHandlingFee() float64 {
	if m != nil {
		return m.MerHandlingFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetMerFee() float64 {
	if m != nil {
		return m.MerFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *MerchantOrderRateListView) GetDesignationNo() string {
	if m != nil {
		return m.DesignationNo
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMaxInternalCharge() float64 {
	if m != nil {
		return m.MaxInternalCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetSingleMinCharge() float64 {
	if m != nil {
		return m.SingleMinCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetSingleMaxCharge() float64 {
	if m != nil {
		return m.SingleMaxCharge
	}
	return 0
}

func (m *MerchantOrderRateListView) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *MerchantOrderRateListView) GetMerchnrateStatus() string {
	if m != nil {
		return m.MerchnrateStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChnStatus() string {
	if m != nil {
		return m.ChnStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetChnIsProxy() string {
	if m != nil {
		return m.ChnIsProxy
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCptStatus() string {
	if m != nil {
		return m.CptStatus
	}
	return ""
}

func (m *MerchantOrderRateListView) GetCptFee() float64 {
	if m != nil {
		return m.CptFee
	}
	return 0
}

func (m *MerchantOrderRateListView) GetCptHandlingFee() float64 {
	if m != nil {
		return m.CptHandlingFee
	}
	return 0
}

type WithdrawOrderRequest struct {
	MerchantCode         string   `protobuf:"bytes,1,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	UserAccount          string   `protobuf:"bytes,2,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	MerchantAccountName  string   `protobuf:"bytes,3,opt,name=MerchantAccountName,proto3" json:"MerchantAccountName,omitempty"`
	MerchantBankeAccount string   `protobuf:"bytes,4,opt,name=MerchantBankeAccount,proto3" json:"MerchantBankeAccount,omitempty"`
	MerchantBankNo       string   `protobuf:"bytes,5,opt,name=MerchantBankNo,proto3" json:"MerchantBankNo,omitempty"`
	MerchantBankName     string   `protobuf:"bytes,6,opt,name=MerchantBankName,proto3" json:"MerchantBankName,omitempty"`
	MerchantBankProvince string   `protobuf:"bytes,7,opt,name=MerchantBankProvince,proto3" json:"MerchantBankProvince,omitempty"`
	MerchantBankCity     string   `protobuf:"bytes,8,opt,name=MerchantBankCity,proto3" json:"MerchantBankCity,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,9,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,10,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	OrderNo              string   `protobuf:"bytes,11,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	HandlingFee          float64  `protobuf:"fixed64,12,opt,name=HandlingFee,proto3" json:"HandlingFee,omitempty"`
	Source               string   `protobuf:"bytes,13,opt,name=Source,proto3" json:"Source,omitempty"`
	MerchantOrderNo      string   `protobuf:"bytes,14,opt,name=MerchantOrderNo,proto3" json:"MerchantOrderNo,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,15,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	PageUrl              string   `protobuf:"bytes,16,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawOrderRequest) Reset()         { *m = WithdrawOrderRequest{} }
func (m *WithdrawOrderRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawOrderRequest) ProtoMessage()    {}
func (*WithdrawOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{12}
}

func (m *WithdrawOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawOrderRequest.Unmarshal(m, b)
}
func (m *WithdrawOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawOrderRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawOrderRequest.Merge(m, src)
}
func (m *WithdrawOrderRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawOrderRequest.Size(m)
}
func (m *WithdrawOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawOrderRequest proto.InternalMessageInfo

func (m *WithdrawOrderRequest) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *WithdrawOrderRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantAccountName() string {
	if m != nil {
		return m.MerchantAccountName
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantBankeAccount() string {
	if m != nil {
		return m.MerchantBankeAccount
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantBankNo() string {
	if m != nil {
		return m.MerchantBankNo
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantBankName() string {
	if m != nil {
		return m.MerchantBankName
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantBankProvince() string {
	if m != nil {
		return m.MerchantBankProvince
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantBankCity() string {
	if m != nil {
		return m.MerchantBankCity
	}
	return ""
}

func (m *WithdrawOrderRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *WithdrawOrderRequest) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *WithdrawOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *WithdrawOrderRequest) GetHandlingFee() float64 {
	if m != nil {
		return m.HandlingFee
	}
	return 0
}

func (m *WithdrawOrderRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *WithdrawOrderRequest) GetMerchantOrderNo() string {
	if m != nil {
		return m.MerchantOrderNo
	}
	return ""
}

func (m *WithdrawOrderRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *WithdrawOrderRequest) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

type WithdrawOrderResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawOrderResponse) Reset()         { *m = WithdrawOrderResponse{} }
func (m *WithdrawOrderResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawOrderResponse) ProtoMessage()    {}
func (*WithdrawOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{13}
}

func (m *WithdrawOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawOrderResponse.Unmarshal(m, b)
}
func (m *WithdrawOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawOrderResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawOrderResponse.Merge(m, src)
}
func (m *WithdrawOrderResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawOrderResponse.Size(m)
}
func (m *WithdrawOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawOrderResponse proto.InternalMessageInfo

func (m *WithdrawOrderResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type PayCallBackRequest struct {
	CallbackTime         string   `protobuf:"bytes,1,opt,name=CallbackTime,proto3" json:"CallbackTime,omitempty"`
	ChannelOrderNo       string   `protobuf:"bytes,2,opt,name=ChannelOrderNo,proto3" json:"ChannelOrderNo,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,3,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	OrderStatus          string   `protobuf:"bytes,4,opt,name=OrderStatus,proto3" json:"OrderStatus,omitempty"`
	PayOrderNo           string   `protobuf:"bytes,5,opt,name=PayOrderNo,proto3" json:"PayOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallBackRequest) Reset()         { *m = PayCallBackRequest{} }
func (m *PayCallBackRequest) String() string { return proto.CompactTextString(m) }
func (*PayCallBackRequest) ProtoMessage()    {}
func (*PayCallBackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{14}
}

func (m *PayCallBackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallBackRequest.Unmarshal(m, b)
}
func (m *PayCallBackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallBackRequest.Marshal(b, m, deterministic)
}
func (m *PayCallBackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallBackRequest.Merge(m, src)
}
func (m *PayCallBackRequest) XXX_Size() int {
	return xxx_messageInfo_PayCallBackRequest.Size(m)
}
func (m *PayCallBackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallBackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallBackRequest proto.InternalMessageInfo

func (m *PayCallBackRequest) GetCallbackTime() string {
	if m != nil {
		return m.CallbackTime
	}
	return ""
}

func (m *PayCallBackRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

func (m *PayCallBackRequest) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *PayCallBackRequest) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *PayCallBackRequest) GetPayOrderNo() string {
	if m != nil {
		return m.PayOrderNo
	}
	return ""
}

type PayCallBackResponse struct {
	MerchantCode         string   `protobuf:"bytes,1,opt,name=MerchantCode,proto3" json:"MerchantCode,omitempty"`
	MerchantOrderNo      string   `protobuf:"bytes,2,opt,name=MerchantOrderNo,proto3" json:"MerchantOrderNo,omitempty"`
	OrderNo              string   `protobuf:"bytes,3,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	OrderAmount          float64  `protobuf:"fixed64,4,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	ActualAmount         float64  `protobuf:"fixed64,5,opt,name=ActualAmount,proto3" json:"ActualAmount,omitempty"`
	TransferHandlingFee  float64  `protobuf:"fixed64,6,opt,name=TransferHandlingFee,proto3" json:"TransferHandlingFee,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,7,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	OrderTime            string   `protobuf:"bytes,8,opt,name=OrderTime,proto3" json:"OrderTime,omitempty"`
	PayOrderTime         string   `protobuf:"bytes,9,opt,name=PayOrderTime,proto3" json:"PayOrderTime,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallBackResponse) Reset()         { *m = PayCallBackResponse{} }
func (m *PayCallBackResponse) String() string { return proto.CompactTextString(m) }
func (*PayCallBackResponse) ProtoMessage()    {}
func (*PayCallBackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{15}
}

func (m *PayCallBackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallBackResponse.Unmarshal(m, b)
}
func (m *PayCallBackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallBackResponse.Marshal(b, m, deterministic)
}
func (m *PayCallBackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallBackResponse.Merge(m, src)
}
func (m *PayCallBackResponse) XXX_Size() int {
	return xxx_messageInfo_PayCallBackResponse.Size(m)
}
func (m *PayCallBackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallBackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallBackResponse proto.InternalMessageInfo

func (m *PayCallBackResponse) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *PayCallBackResponse) GetMerchantOrderNo() string {
	if m != nil {
		return m.MerchantOrderNo
	}
	return ""
}

func (m *PayCallBackResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayCallBackResponse) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *PayCallBackResponse) GetActualAmount() float64 {
	if m != nil {
		return m.ActualAmount
	}
	return 0
}

func (m *PayCallBackResponse) GetTransferHandlingFee() float64 {
	if m != nil {
		return m.TransferHandlingFee
	}
	return 0
}

func (m *PayCallBackResponse) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *PayCallBackResponse) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *PayCallBackResponse) GetPayOrderTime() string {
	if m != nil {
		return m.PayOrderTime
	}
	return ""
}

func (m *PayCallBackResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type InternalReviewSuccessRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	UserAccount          string   `protobuf:"bytes,2,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalReviewSuccessRequest) Reset()         { *m = InternalReviewSuccessRequest{} }
func (m *InternalReviewSuccessRequest) String() string { return proto.CompactTextString(m) }
func (*InternalReviewSuccessRequest) ProtoMessage()    {}
func (*InternalReviewSuccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{16}
}

func (m *InternalReviewSuccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalReviewSuccessRequest.Unmarshal(m, b)
}
func (m *InternalReviewSuccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalReviewSuccessRequest.Marshal(b, m, deterministic)
}
func (m *InternalReviewSuccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalReviewSuccessRequest.Merge(m, src)
}
func (m *InternalReviewSuccessRequest) XXX_Size() int {
	return xxx_messageInfo_InternalReviewSuccessRequest.Size(m)
}
func (m *InternalReviewSuccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalReviewSuccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalReviewSuccessRequest proto.InternalMessageInfo

func (m *InternalReviewSuccessRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *InternalReviewSuccessRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

type InternalReviewSuccessResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalReviewSuccessResponse) Reset()         { *m = InternalReviewSuccessResponse{} }
func (m *InternalReviewSuccessResponse) String() string { return proto.CompactTextString(m) }
func (*InternalReviewSuccessResponse) ProtoMessage()    {}
func (*InternalReviewSuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{17}
}

func (m *InternalReviewSuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalReviewSuccessResponse.Unmarshal(m, b)
}
func (m *InternalReviewSuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalReviewSuccessResponse.Marshal(b, m, deterministic)
}
func (m *InternalReviewSuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalReviewSuccessResponse.Merge(m, src)
}
func (m *InternalReviewSuccessResponse) XXX_Size() int {
	return xxx_messageInfo_InternalReviewSuccessResponse.Size(m)
}
func (m *InternalReviewSuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalReviewSuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalReviewSuccessResponse proto.InternalMessageInfo

func (m *InternalReviewSuccessResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type WithdrawReviewFailRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	UserAccount          string   `protobuf:"bytes,2,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	Memo                 string   `protobuf:"bytes,3,opt,name=Memo,proto3" json:"Memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReviewFailRequest) Reset()         { *m = WithdrawReviewFailRequest{} }
func (m *WithdrawReviewFailRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawReviewFailRequest) ProtoMessage()    {}
func (*WithdrawReviewFailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{18}
}

func (m *WithdrawReviewFailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReviewFailRequest.Unmarshal(m, b)
}
func (m *WithdrawReviewFailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReviewFailRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawReviewFailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReviewFailRequest.Merge(m, src)
}
func (m *WithdrawReviewFailRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawReviewFailRequest.Size(m)
}
func (m *WithdrawReviewFailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReviewFailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReviewFailRequest proto.InternalMessageInfo

func (m *WithdrawReviewFailRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *WithdrawReviewFailRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *WithdrawReviewFailRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type WithdrawReviewFailResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReviewFailResponse) Reset()         { *m = WithdrawReviewFailResponse{} }
func (m *WithdrawReviewFailResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawReviewFailResponse) ProtoMessage()    {}
func (*WithdrawReviewFailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{19}
}

func (m *WithdrawReviewFailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReviewFailResponse.Unmarshal(m, b)
}
func (m *WithdrawReviewFailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReviewFailResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawReviewFailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReviewFailResponse.Merge(m, src)
}
func (m *WithdrawReviewFailResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawReviewFailResponse.Size(m)
}
func (m *WithdrawReviewFailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReviewFailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReviewFailResponse proto.InternalMessageInfo

func (m *WithdrawReviewFailResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type WithdrawReviewSuccessRequest struct {
	OrderNo              string             `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	UserAccount          string             `protobuf:"bytes,2,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	ChannelWithdraw      []*ChannelWithdraw `protobuf:"bytes,3,rep,name=channelWithdraw,proto3" json:"channelWithdraw,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WithdrawReviewSuccessRequest) Reset()         { *m = WithdrawReviewSuccessRequest{} }
func (m *WithdrawReviewSuccessRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawReviewSuccessRequest) ProtoMessage()    {}
func (*WithdrawReviewSuccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{20}
}

func (m *WithdrawReviewSuccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReviewSuccessRequest.Unmarshal(m, b)
}
func (m *WithdrawReviewSuccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReviewSuccessRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawReviewSuccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReviewSuccessRequest.Merge(m, src)
}
func (m *WithdrawReviewSuccessRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawReviewSuccessRequest.Size(m)
}
func (m *WithdrawReviewSuccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReviewSuccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReviewSuccessRequest proto.InternalMessageInfo

func (m *WithdrawReviewSuccessRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *WithdrawReviewSuccessRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *WithdrawReviewSuccessRequest) GetChannelWithdraw() []*ChannelWithdraw {
	if m != nil {
		return m.ChannelWithdraw
	}
	return nil
}

type WithdrawReviewSuccessResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReviewSuccessResponse) Reset()         { *m = WithdrawReviewSuccessResponse{} }
func (m *WithdrawReviewSuccessResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawReviewSuccessResponse) ProtoMessage()    {}
func (*WithdrawReviewSuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{21}
}

func (m *WithdrawReviewSuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReviewSuccessResponse.Unmarshal(m, b)
}
func (m *WithdrawReviewSuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReviewSuccessResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawReviewSuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReviewSuccessResponse.Merge(m, src)
}
func (m *WithdrawReviewSuccessResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawReviewSuccessResponse.Size(m)
}
func (m *WithdrawReviewSuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReviewSuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReviewSuccessResponse proto.InternalMessageInfo

func (m *WithdrawReviewSuccessResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type ChannelWithdraw struct {
	ChannelCode          string   `protobuf:"bytes,1,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	WithdrawAmount       float64  `protobuf:"fixed64,2,opt,name=WithdrawAmount,proto3" json:"WithdrawAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelWithdraw) Reset()         { *m = ChannelWithdraw{} }
func (m *ChannelWithdraw) String() string { return proto.CompactTextString(m) }
func (*ChannelWithdraw) ProtoMessage()    {}
func (*ChannelWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{22}
}

func (m *ChannelWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelWithdraw.Unmarshal(m, b)
}
func (m *ChannelWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelWithdraw.Marshal(b, m, deterministic)
}
func (m *ChannelWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelWithdraw.Merge(m, src)
}
func (m *ChannelWithdraw) XXX_Size() int {
	return xxx_messageInfo_ChannelWithdraw.Size(m)
}
func (m *ChannelWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelWithdraw proto.InternalMessageInfo

func (m *ChannelWithdraw) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *ChannelWithdraw) GetWithdrawAmount() float64 {
	if m != nil {
		return m.WithdrawAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*ProxyOrderRequest)(nil), "transaction.ProxyOrderRequest")
	proto.RegisterType((*ProxyOrderResponse)(nil), "transaction.ProxyOrderResponse")
	proto.RegisterType((*ProxyOrderResp_XFB)(nil), "transaction.ProxyOrderResp_XFB")
	proto.RegisterType((*ProxyPayOrderRequest)(nil), "transaction.ProxyPayOrderRequest")
	proto.RegisterType((*CorrespondMerChnRate)(nil), "transaction.CorrespondMerChnRate")
	proto.RegisterType((*PayOrderRequest)(nil), "transaction.PayOrderRequest")
	proto.RegisterType((*PayOrderResponse)(nil), "transaction.PayOrderResponse")
	proto.RegisterType((*PayOrder)(nil), "transaction.PayOrder")
	proto.RegisterType((*InternalOrderRequest)(nil), "transaction.InternalOrderRequest")
	proto.RegisterType((*InternalOrderResponse)(nil), "transaction.InternalOrderResponse")
	proto.RegisterType((*InternalOrder)(nil), "transaction.InternalOrder")
	proto.RegisterType((*MerchantOrderRateListView)(nil), "transaction.MerchantOrderRateListView")
	proto.RegisterType((*WithdrawOrderRequest)(nil), "transaction.WithdrawOrderRequest")
	proto.RegisterType((*WithdrawOrderResponse)(nil), "transaction.WithdrawOrderResponse")
	proto.RegisterType((*PayCallBackRequest)(nil), "transaction.PayCallBackRequest")
	proto.RegisterType((*PayCallBackResponse)(nil), "transaction.PayCallBackResponse")
	proto.RegisterType((*InternalReviewSuccessRequest)(nil), "transaction.InternalReviewSuccessRequest")
	proto.RegisterType((*InternalReviewSuccessResponse)(nil), "transaction.InternalReviewSuccessResponse")
	proto.RegisterType((*WithdrawReviewFailRequest)(nil), "transaction.WithdrawReviewFailRequest")
	proto.RegisterType((*WithdrawReviewFailResponse)(nil), "transaction.WithdrawReviewFailResponse")
	proto.RegisterType((*WithdrawReviewSuccessRequest)(nil), "transaction.WithdrawReviewSuccessRequest")
	proto.RegisterType((*WithdrawReviewSuccessResponse)(nil), "transaction.WithdrawReviewSuccessResponse")
	proto.RegisterType((*ChannelWithdraw)(nil), "transaction.ChannelWithdraw")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 1788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0x86, 0x5e, 0x96, 0x75, 0xe4, 0xe7, 0x58, 0x09, 0x18, 0xc1, 0x49, 0x14, 0xe2, 0xc2, 0xd7,
	0x37, 0xb8, 0x70, 0x13, 0x07, 0x2d, 0xda, 0x5d, 0x6d, 0xa5, 0x46, 0x5d, 0x58, 0xaa, 0x4b, 0x3b,
	0x6d, 0x90, 0x2c, 0x82, 0x31, 0x35, 0x91, 0x08, 0x4b, 0xa4, 0x42, 0x51, 0x49, 0xf4, 0x6f, 0xda,
	0xa2, 0x7f, 0xa3, 0x45, 0x17, 0x5d, 0x77, 0xd3, 0xdf, 0xd1, 0x4d, 0xb7, 0xdd, 0x14, 0xf3, 0x12,
	0x67, 0x86, 0x43, 0x5b, 0x41, 0xbd, 0xf3, 0xf9, 0xce, 0x99, 0x33, 0xaf, 0xef, 0x7c, 0x73, 0x28,
	0xc3, 0x66, 0x12, 0xe3, 0x70, 0x82, 0xfd, 0x24, 0x88, 0xc2, 0xbd, 0x71, 0x1c, 0x25, 0x11, 0xaa,
	0x2b, 0x90, 0xfb, 0x43, 0x01, 0x36, 0x4f, 0xe3, 0xe8, 0xfd, 0xec, 0xeb, 0xb8, 0x47, 0x62, 0x8f,
	0xbc, 0x99, 0x92, 0x49, 0x82, 0x9e, 0x40, 0x29, 0x26, 0x6f, 0x9c, 0x42, 0xab, 0xb0, 0x5b, 0xdf,
	0x7f, 0xb0, 0xa7, 0xe6, 0x60, 0xc1, 0xa7, 0x58, 0x8b, 0xf7, 0x68, 0x34, 0xfa, 0x18, 0xca, 0x31,
	0x4e, 0x88, 0x53, 0xb4, 0x8c, 0x6a, 0x47, 0x71, 0x4c, 0x26, 0xe3, 0x28, 0xec, 0x75, 0x48, 0xdc,
	0x1e, 0x84, 0x1e, 0x4e, 0x88, 0xc7, 0xc2, 0x51, 0x0b, 0xea, 0x17, 0x78, 0x88, 0x43, 0x9f, 0x9c,
	0xcf, 0xc6, 0xc4, 0x29, 0xb5, 0x0a, 0xbb, 0x35, 0x4f, 0x85, 0xdc, 0x4f, 0x01, 0xa9, 0x4b, 0xa4,
	0x69, 0x26, 0x04, 0xb9, 0xb0, 0x92, 0xa2, 0xdd, 0x88, 0x2d, 0xb6, 0xe6, 0x69, 0x58, 0x76, 0xe4,
	0xab, 0xe7, 0x47, 0x87, 0x0b, 0x8d, 0xfc, 0xbd, 0x0c, 0x0d, 0xdb, 0x56, 0xd1, 0x3d, 0x80, 0x03,
	0xdf, 0x27, 0x93, 0x09, 0x5b, 0x2d, 0x1f, 0xaa, 0x20, 0xd4, 0xdf, 0x21, 0xb1, 0x3f, 0xc0, 0x61,
	0x72, 0xdc, 0x63, 0x67, 0x51, 0xf3, 0x14, 0x04, 0x21, 0x28, 0x9f, 0x05, 0xfd, 0x50, 0xec, 0x93,
	0xfd, 0x8d, 0xb6, 0xa1, 0xd6, 0x8d, 0x92, 0xe0, 0xf5, 0xec, 0x59, 0x3c, 0x74, 0xca, 0xcc, 0x91,
	0x02, 0xa8, 0x09, 0xcb, 0x27, 0x38, 0xec, 0x4f, 0x71, 0x9f, 0x38, 0x15, 0xe6, 0x9c, 0xdb, 0xc8,
	0x81, 0xaa, 0xdc, 0xc5, 0x12, 0x73, 0x49, 0x13, 0xdd, 0x86, 0xa5, 0x43, 0x1c, 0x5e, 0x1e, 0xf7,
	0x9c, 0x2a, 0x73, 0x08, 0x8b, 0x66, 0xa3, 0x7f, 0x75, 0xf1, 0x88, 0x38, 0xcb, 0x3c, 0x9b, 0xb4,
	0xe9, 0xc1, 0xd0, 0xbf, 0x4f, 0xe3, 0xe8, 0x6d, 0x10, 0xfa, 0xc4, 0xa9, 0xf1, 0x83, 0x51, 0x31,
	0x39, 0xbe, 0x1d, 0x24, 0x33, 0x07, 0xd2, 0xf1, 0xd4, 0xa6, 0x7b, 0x3f, 0x8c, 0x71, 0xe8, 0x0f,
	0x58, 0xf6, 0x3a, 0xdf, 0x7b, 0x8a, 0xc8, 0x35, 0x75, 0x23, 0x67, 0x25, 0x5d, 0x53, 0x37, 0xa2,
	0x14, 0x60, 0xcb, 0x3e, 0x18, 0x45, 0xd3, 0x30, 0x71, 0x56, 0x5b, 0x85, 0xdd, 0x82, 0xa7, 0x42,
	0x34, 0xf3, 0x53, 0xf2, 0x3a, 0xc6, 0x33, 0x96, 0x79, 0x8d, 0x67, 0x4e, 0x11, 0xba, 0x2a, 0x6e,
	0x1d, 0xf7, 0x9c, 0x75, 0xbe, 0x2a, 0x69, 0xd3, 0x5d, 0xf1, 0xbf, 0x3b, 0xd1, 0x45, 0x30, 0x24,
	0xce, 0x06, 0xdf, 0x95, 0x8a, 0xd1, 0x15, 0x70, 0xfb, 0x8b, 0x11, 0x0e, 0x86, 0xce, 0x26, 0x27,
	0xa1, 0x02, 0xd1, 0x19, 0xda, 0xd3, 0x38, 0x26, 0xa1, 0x3f, 0x73, 0x10, 0x9f, 0x41, 0xda, 0x8c,
	0x50, 0x78, 0x46, 0xaf, 0xff, 0x6c, 0x7a, 0xd1, 0x8d, 0x9c, 0x2d, 0x41, 0x28, 0x05, 0x73, 0xbf,
	0x2f, 0x43, 0xc3, 0x56, 0x05, 0x74, 0xb0, 0xa4, 0x47, 0x3b, 0xea, 0x49, 0x4a, 0x69, 0x18, 0x7a,
	0x04, 0x5b, 0xed, 0x01, 0x0e, 0x43, 0x32, 0x14, 0x39, 0x27, 0x2c, 0x94, 0xb3, 0xcb, 0xe6, 0xa2,
	0x1b, 0x12, 0x30, 0x8b, 0x14, 0x55, 0xa5, 0x40, 0x34, 0x42, 0x8c, 0x60, 0x11, 0x9c, 0x76, 0x2a,
	0x84, 0x76, 0x60, 0x4d, 0x31, 0xbb, 0xd3, 0x91, 0xa0, 0x9f, 0x81, 0xf2, 0xc3, 0x9b, 0x04, 0xfd,
	0x10, 0xd3, 0x5a, 0x17, 0x44, 0x54, 0x21, 0xf4, 0x1f, 0x58, 0x55, 0xcc, 0x6e, 0x24, 0x38, 0xa9,
	0x83, 0x68, 0x03, 0x4a, 0x47, 0x84, 0xb3, 0xb2, 0xe0, 0xd1, 0x3f, 0x69, 0xe6, 0x2f, 0x71, 0xd8,
	0x1b, 0x06, 0x61, 0x9f, 0x7a, 0x6a, 0x9c, 0x18, 0x0a, 0x84, 0x1a, 0x50, 0x69, 0x0f, 0xa8, 0x0f,
	0x98, 0x8f, 0x1b, 0x74, 0xbe, 0xf6, 0x40, 0x1d, 0x59, 0x67, 0x5e, 0x1d, 0x44, 0xbb, 0xb0, 0x7e,
	0x16, 0x84, 0xfd, 0x21, 0xe9, 0x04, 0x61, 0x7b, 0x80, 0xe3, 0x3e, 0x61, 0xbc, 0x2c, 0x78, 0x26,
	0xac, 0x44, 0xe2, 0xf7, 0x22, 0x72, 0x55, 0x8b, 0x94, 0x30, 0xbd, 0x4d, 0x49, 0x0b, 0x76, 0xac,
	0x9c, 0xaa, 0x1a, 0x46, 0xcb, 0xe0, 0x60, 0x1c, 0xd0, 0x5a, 0xe7, 0x54, 0x15, 0x96, 0xfb, 0x73,
	0x01, 0xd6, 0x4d, 0xb9, 0x79, 0x0c, 0xcb, 0x63, 0x01, 0x09, 0x39, 0xbe, 0xa5, 0xcb, 0xb1, 0x8c,
	0x9f, 0x87, 0x51, 0x1d, 0xf6, 0x3e, 0x4c, 0x87, 0x19, 0x0f, 0x15, 0x29, 0x29, 0xe9, 0x52, 0xb2,
	0x03, 0x6b, 0x82, 0x38, 0x32, 0x80, 0x93, 0xc5, 0x40, 0xdd, 0x7d, 0xd8, 0x48, 0x97, 0x2f, 0x54,
	0xfa, 0x1e, 0x80, 0xc4, 0xe6, 0x4a, 0xab, 0x20, 0xee, 0xaf, 0x65, 0x58, 0x96, 0xe6, 0xbf, 0xd6,
	0x56, 0x4d, 0x47, 0x4b, 0xa6, 0x8e, 0x3a, 0x50, 0x3d, 0xc5, 0x7d, 0x92, 0x6a, 0xac, 0x34, 0xaf,
	0x54, 0x58, 0xa9, 0xd7, 0x4b, 0x8a, 0x5e, 0x37, 0x61, 0xf9, 0xab, 0xe9, 0x68, 0xcc, 0x56, 0xc9,
	0x99, 0x3c, 0xb7, 0xe9, 0x1a, 0x4e, 0xa2, 0x7e, 0x10, 0x32, 0x27, 0x17, 0xd8, 0x14, 0x50, 0x0f,
	0xb9, 0xa6, 0x1f, 0xb2, 0xa1, 0x81, 0x5c, 0x5a, 0x35, 0x0d, 0x54, 0x15, 0xa8, 0x6e, 0x28, 0x10,
	0xdb, 0x1b, 0x2b, 0x4a, 0x21, 0xad, 0xd2, 0xa4, 0xeb, 0x61, 0x49, 0xce, 0x83, 0x11, 0x27, 0x6d,
	0xcd, 0x4b, 0x81, 0xb9, 0x57, 0x91, 0xd5, 0x14, 0x98, 0x6b, 0x3d, 0x25, 0xf2, 0xba, 0xa2, 0xf5,
	0x94, 0xc4, 0x0d, 0xa8, 0x9c, 0x0e, 0xa2, 0x50, 0xca, 0x29, 0x37, 0x68, 0x3e, 0x31, 0x71, 0x37,
	0x12, 0x2a, 0x9a, 0x02, 0x94, 0xf8, 0xcf, 0x26, 0x24, 0x3e, 0xee, 0x09, 0x05, 0x15, 0x16, 0x2d,
	0x57, 0x79, 0x8b, 0x27, 0xe4, 0x2d, 0x19, 0x0a, 0x01, 0xd5, 0xc1, 0xf9, 0xe8, 0xb1, 0xd3, 0x50,
	0x46, 0x8f, 0xdd, 0x5f, 0x0a, 0xd0, 0x38, 0x0e, 0x13, 0x12, 0x87, 0x78, 0xa8, 0xd5, 0xce, 0xe7,
	0xb0, 0x1a, 0xa8, 0xb8, 0x28, 0xa0, 0xa6, 0x56, 0x11, 0xfa, 0x48, 0x7d, 0x00, 0xea, 0xc1, 0x9d,
	0x91, 0x58, 0x03, 0xf7, 0xe3, 0x84, 0x9c, 0x04, 0x93, 0xe4, 0xdb, 0x80, 0xbc, 0x13, 0xf5, 0xb5,
	0xa3, 0x65, 0xeb, 0xe4, 0x45, 0x7b, 0xf9, 0x89, 0xdc, 0xc7, 0x70, 0xcb, 0x58, 0xbf, 0x28, 0x1e,
	0x07, 0xaa, 0x91, 0x56, 0x39, 0xd2, 0x74, 0xff, 0x2e, 0xc3, 0xaa, 0x36, 0x86, 0x9e, 0xce, 0xf1,
	0xa8, 0x3f, 0x8d, 0x87, 0x22, 0x54, 0x58, 0x99, 0xe7, 0xa5, 0x68, 0x79, 0x5e, 0x5a, 0x50, 0xa7,
	0x67, 0x79, 0xe0, 0xfb, 0x8c, 0x7b, 0xe2, 0xb1, 0x50, 0x20, 0x93, 0x9d, 0xe5, 0xec, 0x0b, 0x6d,
	0x0a, 0x5f, 0xc5, 0x22, 0x7c, 0x8f, 0x60, 0x4b, 0xce, 0x2b, 0x12, 0x33, 0xde, 0xf1, 0xd2, 0xb2,
	0xb9, 0xd4, 0x11, 0x94, 0x79, 0x72, 0x85, 0x55, 0x7d, 0x84, 0xe2, 0x42, 0x0f, 0x61, 0x43, 0x85,
	0x59, 0x9f, 0xc2, 0xcb, 0x30, 0x83, 0xa3, 0x7d, 0x68, 0x8c, 0x14, 0xcc, 0xe8, 0x7b, 0xac, 0x3e,
	0x2a, 0x86, 0x6a, 0x9e, 0x6e, 0x24, 0x4a, 0xd5, 0x40, 0xcd, 0x75, 0x28, 0x1d, 0x51, 0x06, 0xa7,
	0xcf, 0x8b, 0x90, 0xd2, 0x79, 0x28, 0xaf, 0x62, 0x13, 0x46, 0x7b, 0x80, 0x04, 0xa4, 0x1e, 0x20,
	0x2f, 0x6b, 0x8b, 0x47, 0x89, 0x57, 0x8f, 0x6f, 0x4d, 0x8b, 0x57, 0x4f, 0x8f, 0x3d, 0x9c, 0xe9,
	0x94, 0x91, 0x28, 0x7b, 0x1d, 0x74, 0xff, 0xa8, 0xc0, 0x9d, 0x5c, 0xa6, 0xe7, 0x35, 0x2b, 0x85,
	0x2b, 0x9b, 0x15, 0xb5, 0x15, 0x29, 0x2e, 0xd2, 0x8a, 0x94, 0xac, 0xad, 0x08, 0xbf, 0x1d, 0xf5,
	0xe5, 0xe7, 0x54, 0x35, 0x50, 0x5a, 0x2d, 0x1d, 0x12, 0x53, 0x7f, 0x85, 0xf9, 0x85, 0x75, 0x63,
	0xad, 0x8c, 0xd1, 0x7e, 0x2d, 0x67, 0xdb, 0x2f, 0xb3, 0x5e, 0x6a, 0x96, 0x7a, 0xf9, 0x3f, 0x6c,
	0x76, 0xf0, 0x7b, 0x59, 0xe7, 0xa2, 0xf1, 0xe0, 0x8d, 0x4e, 0xd6, 0x61, 0x6b, 0x67, 0xea, 0x0b,
	0xb7, 0x33, 0x2b, 0xb9, 0xed, 0x8c, 0xa6, 0x1e, 0xab, 0x16, 0xf5, 0x90, 0x4c, 0x0f, 0xe9, 0xe7,
	0xdc, 0x59, 0x82, 0x93, 0xe9, 0x44, 0x30, 0x2c, 0x83, 0xd3, 0xf7, 0xa1, 0x3d, 0x08, 0x45, 0x10,
	0xe7, 0x56, 0x0a, 0xd0, 0xf7, 0xbd, 0x3d, 0x08, 0x8f, 0x27, 0xec, 0xc3, 0x4b, 0x3c, 0x2c, 0x0a,
	0xc2, 0x46, 0x8f, 0x13, 0x31, 0x5a, 0xbc, 0x2e, 0x73, 0x80, 0xde, 0x69, 0x7b, 0x9c, 0xd0, 0x3b,
	0x45, 0xfc, 0x4e, 0xb9, 0xc5, 0xda, 0x97, 0x71, 0xa2, 0x72, 0x62, 0x8b, 0x73, 0x42, 0x47, 0xdd,
	0xbf, 0xca, 0xd0, 0xf8, 0x2e, 0x48, 0x06, 0xbd, 0x18, 0xbf, 0xd3, 0xde, 0x91, 0x45, 0x3a, 0x74,
	0x43, 0x42, 0x8b, 0x59, 0x09, 0xcd, 0x11, 0xbf, 0x52, 0xbe, 0xf8, 0xed, 0x43, 0x43, 0x95, 0x0a,
	0x22, 0x93, 0xf3, 0xee, 0xc5, 0xea, 0xb3, 0xc8, 0x53, 0x65, 0x61, 0x79, 0x5a, 0xca, 0x91, 0x27,
	0x63, 0x1d, 0x73, 0x99, 0xac, 0x66, 0xd7, 0x31, 0x97, 0xc9, 0x0f, 0x91, 0xe1, 0x45, 0x4a, 0xc1,
	0xd2, 0x1e, 0x19, 0x0f, 0x90, 0xd2, 0x5a, 0xd5, 0x33, 0xad, 0x95, 0x7a, 0xfb, 0x2b, 0xd9, 0xaf,
	0x88, 0xdb, 0xb0, 0x74, 0x16, 0x4d, 0x63, 0x5f, 0x12, 0x5c, 0x58, 0xb4, 0x50, 0x34, 0x9d, 0xeb,
	0x46, 0x82, 0xd9, 0x26, 0xac, 0xb7, 0x9e, 0xeb, 0x57, 0xb4, 0x9e, 0x1b, 0x5a, 0xeb, 0x49, 0xdf,
	0x7e, 0x83, 0x73, 0xe9, 0xdb, 0xaf, 0x77, 0xcd, 0xd2, 0x74, 0x7f, 0x2b, 0x00, 0x3a, 0xc5, 0xb3,
	0x36, 0x1e, 0x0e, 0x0f, 0xb1, 0x7f, 0xa9, 0xb0, 0x94, 0x42, 0x17, 0xd8, 0xbf, 0x64, 0xbd, 0x9e,
	0x60, 0xa9, 0x8a, 0x59, 0x3a, 0xf9, 0xa2, 0xad, 0x93, 0x37, 0x4f, 0xbb, 0x94, 0x3d, 0x6d, 0x19,
	0x21, 0x8a, 0xb1, 0xac, 0xb4, 0xab, 0x69, 0x31, 0x2b, 0x9d, 0x7f, 0x25, 0xd3, 0xf9, 0xff, 0x59,
	0x84, 0x2d, 0x6d, 0x1b, 0xe9, 0xef, 0x3a, 0xd7, 0x56, 0x9b, 0xe5, 0x5e, 0x8a, 0xf6, 0x7b, 0xc9,
	0xff, 0xaa, 0x59, 0xa8, 0xa5, 0x39, 0xf0, 0x93, 0x29, 0x1e, 0x8a, 0x10, 0xfe, 0x54, 0x68, 0x18,
	0xad, 0xea, 0x73, 0xda, 0xff, 0xbd, 0xd6, 0x5f, 0x9d, 0x25, 0x16, 0x6a, 0x73, 0xe9, 0x4c, 0xa9,
	0x9a, 0x4c, 0xd1, 0xda, 0xf5, 0x65, 0xb3, 0x5d, 0xe7, 0x3f, 0x34, 0xa4, 0x01, 0xb5, 0xf9, 0x0f,
	0x0d, 0x69, 0x0c, 0xe5, 0x32, 0xbf, 0x14, 0x10, 0x5c, 0x66, 0x96, 0xfb, 0x02, 0xb6, 0xe5, 0x83,
	0xe1, 0x91, 0xb7, 0x01, 0x79, 0x77, 0x36, 0x65, 0x5f, 0x56, 0x92, 0x3f, 0xb9, 0x84, 0xbb, 0x5e,
	0xdb, 0xdc, 0xcf, 0xe0, 0x6e, 0x4e, 0xee, 0x6b, 0xd9, 0x7c, 0x09, 0x77, 0x64, 0x01, 0xf0, 0xa1,
	0x47, 0x38, 0x18, 0xde, 0xc0, 0x9a, 0xe8, 0x87, 0x5b, 0x87, 0x8c, 0xe4, 0xb5, 0xb3, 0xbf, 0xdd,
	0x4f, 0xa0, 0x69, 0x9b, 0xec, 0xda, 0x45, 0xfe, 0x58, 0x80, 0x6d, 0x7d, 0xe0, 0xcd, 0x1d, 0x1e,
	0x3a, 0x82, 0x75, 0x9f, 0x97, 0x9f, 0x9c, 0xc2, 0x29, 0xb5, 0x4a, 0xbb, 0xf5, 0xfd, 0x6d, 0xfd,
	0xd3, 0x5d, 0x8f, 0xf1, 0xcc, 0x41, 0xf4, 0x12, 0x72, 0xd6, 0x78, 0xed, 0xfe, 0x5e, 0xce, 0x1b,
	0x50, 0x99, 0xc1, 0xec, 0x60, 0x0a, 0xd9, 0x0e, 0x66, 0x07, 0xd6, 0x64, 0xb4, 0x28, 0x90, 0x22,
	0x7f, 0x57, 0x75, 0x74, 0xff, 0xa7, 0x2a, 0xd4, 0xcf, 0xd3, 0x8d, 0xa0, 0x97, 0xe0, 0xa4, 0x3f,
	0xb5, 0x52, 0x07, 0xc7, 0x5f, 0x3d, 0x3d, 0x3a, 0x44, 0xf7, 0xb2, 0xbf, 0x35, 0xab, 0x4f, 0x71,
	0xf3, 0x7e, 0xae, 0x5f, 0xec, 0x31, 0x2f, 0xf9, 0xf3, 0x9b, 0x48, 0xfe, 0x0d, 0x13, 0x5e, 0x23,
	0x35, 0xda, 0xb6, 0xff, 0x20, 0x23, 0x92, 0xde, 0xcd, 0xf1, 0x8a, 0x94, 0x18, 0x1c, 0xed, 0x3b,
	0x4e, 0x3d, 0xa8, 0x07, 0x57, 0x7c, 0xa8, 0x8a, 0xec, 0xee, 0x55, 0x21, 0xe9, 0x14, 0xda, 0x13,
	0x93, 0x3f, 0x85, 0xad, 0xfb, 0x31, 0xa6, 0xb0, 0x3f, 0x56, 0x2f, 0xe0, 0x96, 0x22, 0xe5, 0xca,
	0xd9, 0xdc, 0x37, 0x77, 0x6f, 0xbc, 0x5a, 0xcd, 0x56, 0x7e, 0x80, 0xc8, 0x3d, 0x83, 0x96, 0x55,
	0x5b, 0xd4, 0x6d, 0xfc, 0xcf, 0x7a, 0x0c, 0xb6, 0x4a, 0x6d, 0x3e, 0x5c, 0x24, 0x54, 0x4c, 0x3d,
	0x36, 0x2b, 0x8a, 0xca, 0x85, 0x3a, 0xef, 0x8e, 0xf5, 0x6c, 0x32, 0x3a, 0xd6, 0xfc, 0xef, 0xb5,
	0x71, 0xe9, 0x66, 0xad, 0x35, 0x9c, 0xbf, 0xd9, 0xab, 0x64, 0xc9, 0xd8, 0xec, 0x95, 0xea, 0x70,
	0xb8, 0xfe, 0x62, 0x75, 0xef, 0x23, 0x25, 0xfc, 0x62, 0x89, 0xfd, 0xbb, 0xe8, 0xc9, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x1d, 0x2a, 0x95, 0xee, 0x43, 0x1a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	ProxyOrderTranaction_DFB(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error)
	ProxyOrderTranaction_XFB(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error)
	PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error)
	InternalOrderTransaction(ctx context.Context, in *InternalOrderRequest, opts ...grpc.CallOption) (*InternalOrderResponse, error)
	WithdrawOrderTransaction(ctx context.Context, in *WithdrawOrderRequest, opts ...grpc.CallOption) (*WithdrawOrderResponse, error)
	PayCallBackTranaction(ctx context.Context, in *PayCallBackRequest, opts ...grpc.CallOption) (*PayCallBackResponse, error)
	InternalReviewSuccessTransaction(ctx context.Context, in *InternalReviewSuccessRequest, opts ...grpc.CallOption) (*InternalReviewSuccessResponse, error)
	WithdrawReviewFailTransaction(ctx context.Context, in *WithdrawReviewFailRequest, opts ...grpc.CallOption) (*WithdrawReviewFailResponse, error)
	WithdrawReviewSuccessTransaction(ctx context.Context, in *WithdrawReviewSuccessRequest, opts ...grpc.CallOption) (*WithdrawReviewSuccessResponse, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) ProxyOrderTranaction_DFB(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error) {
	out := new(ProxyOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/ProxyOrderTranaction_DFB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) ProxyOrderTranaction_XFB(ctx context.Context, in *ProxyOrderRequest, opts ...grpc.CallOption) (*ProxyOrderResponse, error) {
	out := new(ProxyOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/ProxyOrderTranaction_XFB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) PayOrderTranaction(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error) {
	out := new(PayOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/PayOrderTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) InternalOrderTransaction(ctx context.Context, in *InternalOrderRequest, opts ...grpc.CallOption) (*InternalOrderResponse, error) {
	out := new(InternalOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/InternalOrderTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) WithdrawOrderTransaction(ctx context.Context, in *WithdrawOrderRequest, opts ...grpc.CallOption) (*WithdrawOrderResponse, error) {
	out := new(WithdrawOrderResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/WithdrawOrderTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) PayCallBackTranaction(ctx context.Context, in *PayCallBackRequest, opts ...grpc.CallOption) (*PayCallBackResponse, error) {
	out := new(PayCallBackResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/PayCallBackTranaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) InternalReviewSuccessTransaction(ctx context.Context, in *InternalReviewSuccessRequest, opts ...grpc.CallOption) (*InternalReviewSuccessResponse, error) {
	out := new(InternalReviewSuccessResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/InternalReviewSuccessTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) WithdrawReviewFailTransaction(ctx context.Context, in *WithdrawReviewFailRequest, opts ...grpc.CallOption) (*WithdrawReviewFailResponse, error) {
	out := new(WithdrawReviewFailResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/WithdrawReviewFailTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) WithdrawReviewSuccessTransaction(ctx context.Context, in *WithdrawReviewSuccessRequest, opts ...grpc.CallOption) (*WithdrawReviewSuccessResponse, error) {
	out := new(WithdrawReviewSuccessResponse)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/WithdrawReviewSuccessTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	ProxyOrderTranaction_DFB(context.Context, *ProxyOrderRequest) (*ProxyOrderResponse, error)
	ProxyOrderTranaction_XFB(context.Context, *ProxyOrderRequest) (*ProxyOrderResponse, error)
	PayOrderTranaction(context.Context, *PayOrderRequest) (*PayOrderResponse, error)
	InternalOrderTransaction(context.Context, *InternalOrderRequest) (*InternalOrderResponse, error)
	WithdrawOrderTransaction(context.Context, *WithdrawOrderRequest) (*WithdrawOrderResponse, error)
	PayCallBackTranaction(context.Context, *PayCallBackRequest) (*PayCallBackResponse, error)
	InternalReviewSuccessTransaction(context.Context, *InternalReviewSuccessRequest) (*InternalReviewSuccessResponse, error)
	WithdrawReviewFailTransaction(context.Context, *WithdrawReviewFailRequest) (*WithdrawReviewFailResponse, error)
	WithdrawReviewSuccessTransaction(context.Context, *WithdrawReviewSuccessRequest) (*WithdrawReviewSuccessResponse, error)
}

// UnimplementedTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (*UnimplementedTransactionServer) ProxyOrderTranaction_DFB(ctx context.Context, req *ProxyOrderRequest) (*ProxyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyOrderTranaction_DFB not implemented")
}
func (*UnimplementedTransactionServer) ProxyOrderTranaction_XFB(ctx context.Context, req *ProxyOrderRequest) (*ProxyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyOrderTranaction_XFB not implemented")
}
func (*UnimplementedTransactionServer) PayOrderTranaction(ctx context.Context, req *PayOrderRequest) (*PayOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrderTranaction not implemented")
}
func (*UnimplementedTransactionServer) InternalOrderTransaction(ctx context.Context, req *InternalOrderRequest) (*InternalOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalOrderTransaction not implemented")
}
func (*UnimplementedTransactionServer) WithdrawOrderTransaction(ctx context.Context, req *WithdrawOrderRequest) (*WithdrawOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawOrderTransaction not implemented")
}
func (*UnimplementedTransactionServer) PayCallBackTranaction(ctx context.Context, req *PayCallBackRequest) (*PayCallBackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayCallBackTranaction not implemented")
}
func (*UnimplementedTransactionServer) InternalReviewSuccessTransaction(ctx context.Context, req *InternalReviewSuccessRequest) (*InternalReviewSuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalReviewSuccessTransaction not implemented")
}
func (*UnimplementedTransactionServer) WithdrawReviewFailTransaction(ctx context.Context, req *WithdrawReviewFailRequest) (*WithdrawReviewFailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawReviewFailTransaction not implemented")
}
func (*UnimplementedTransactionServer) WithdrawReviewSuccessTransaction(ctx context.Context, req *WithdrawReviewSuccessRequest) (*WithdrawReviewSuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawReviewSuccessTransaction not implemented")
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_ProxyOrderTranaction_DFB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).ProxyOrderTranaction_DFB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/ProxyOrderTranaction_DFB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).ProxyOrderTranaction_DFB(ctx, req.(*ProxyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_ProxyOrderTranaction_XFB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).ProxyOrderTranaction_XFB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/ProxyOrderTranaction_XFB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).ProxyOrderTranaction_XFB(ctx, req.(*ProxyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_PayOrderTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).PayOrderTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/PayOrderTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).PayOrderTranaction(ctx, req.(*PayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_InternalOrderTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).InternalOrderTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/InternalOrderTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).InternalOrderTransaction(ctx, req.(*InternalOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_WithdrawOrderTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).WithdrawOrderTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/WithdrawOrderTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).WithdrawOrderTransaction(ctx, req.(*WithdrawOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_PayCallBackTranaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayCallBackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).PayCallBackTranaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/PayCallBackTranaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).PayCallBackTranaction(ctx, req.(*PayCallBackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_InternalReviewSuccessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalReviewSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).InternalReviewSuccessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/InternalReviewSuccessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).InternalReviewSuccessTransaction(ctx, req.(*InternalReviewSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_WithdrawReviewFailTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReviewFailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).WithdrawReviewFailTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/WithdrawReviewFailTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).WithdrawReviewFailTransaction(ctx, req.(*WithdrawReviewFailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_WithdrawReviewSuccessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReviewSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).WithdrawReviewSuccessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/WithdrawReviewSuccessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).WithdrawReviewSuccessTransaction(ctx, req.(*WithdrawReviewSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyOrderTranaction_DFB",
			Handler:    _Transaction_ProxyOrderTranaction_DFB_Handler,
		},
		{
			MethodName: "ProxyOrderTranaction_XFB",
			Handler:    _Transaction_ProxyOrderTranaction_XFB_Handler,
		},
		{
			MethodName: "PayOrderTranaction",
			Handler:    _Transaction_PayOrderTranaction_Handler,
		},
		{
			MethodName: "InternalOrderTransaction",
			Handler:    _Transaction_InternalOrderTransaction_Handler,
		},
		{
			MethodName: "WithdrawOrderTransaction",
			Handler:    _Transaction_WithdrawOrderTransaction_Handler,
		},
		{
			MethodName: "PayCallBackTranaction",
			Handler:    _Transaction_PayCallBackTranaction_Handler,
		},
		{
			MethodName: "InternalReviewSuccessTransaction",
			Handler:    _Transaction_InternalReviewSuccessTransaction_Handler,
		},
		{
			MethodName: "WithdrawReviewFailTransaction",
			Handler:    _Transaction_WithdrawReviewFailTransaction_Handler,
		},
		{
			MethodName: "WithdrawReviewSuccessTransaction",
			Handler:    _Transaction_WithdrawReviewSuccessTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
